modules/portal/app/controllers/portal/social/Social.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
modules/portal/app/views/userProfile/itemWatchList.scala.html
modules/portal/app/views/userProfile/userWatchList.scala.html
modules/portal/app/views/userProfile/watched.scala.html
modules/portal/app/views/userProfile/watchedItems.scala.html

At the expense of making the templates more complex.

Fix conflation of another user's watched items and our own. Fixes #581.

---

modules/portal/app/views/social/mail/messageEmail.scala.html

Render HTML message body as markdown.

---

modules/portal/app/assets/css/portal/_index.less

CSS tweak to prevent modal backdrops overlaying the content

---

modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/controllers/base/SessionPreferences.scala
modules/core/app/controllers/generic/Creator.scala
modules/core/app/controllers/generic/Descriptions.scala
modules/core/app/controllers/generic/Linking.scala
modules/core/app/controllers/generic/Membership.scala
modules/core/app/controllers/generic/PermissionHolder.scala
modules/core/app/controllers/generic/Search.scala
modules/core/app/controllers/generic/Update.scala
modules/core/app/controllers/generic/Visibility.scala
modules/portal/app/controllers/portal/Bookmarks.scala
modules/portal/app/controllers/portal/Concepts.scala
modules/portal/app/controllers/portal/Feedback.scala
modules/portal/app/controllers/portal/Groups.scala
modules/portal/app/controllers/portal/Helpdesk.scala
modules/portal/app/controllers/portal/HistoricalAgents.scala
modules/portal/app/controllers/portal/Links.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/VirtualUnits.scala
modules/portal/app/controllers/portal/Vocabularies.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/annotate/Annotations.scala
modules/portal/app/controllers/portal/base/PortalAuthConfigImpl.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
modules/portal/conf/messages

- minor cleanups and doc fixes
- add protected to various action builders: in addition being more consistent this also helps distinguish them from actions
- cleaned up imports in portal module

Controller cleanups

---

project/Build.scala

This release include the following possibly-useful changes:
- separates `LoginLogout` trait into `Login` and `Logout`
- adds a way of doing a "remember me" feature

Update play2-auth to 0.13.2

---

modules/admin/app/views/admin/annotation/show.scala.html
modules/admin/app/views/admin/common/annotated.scala.html
modules/admin/conf/messages

Slight tweak to admin annotation view.

---

modules/portal/app/controllers/base/SearchVC.scala
test/integration/portal/VirtualUnitsSpec.scala

Add a test that would've shown the problem.
Fixes #603.

Modify Cypher syntax for Neo4j 2.2.

---

modules/portal/app/views/PegDownMarkdownRenderer.scala

At least this time it's in a nicer place, rather than in with a load of static view functions.

Reintroduce the unfortunately PegDown thread local.

---

modules/portal/app/views/country/listItemBody.scala.html
modules/portal/app/views/country/listItemMeta.scala.html
modules/portal/app/views/documentaryUnit/listItemMeta.scala.html

Adds a country code and last-updated info to country list.

Add some list metadata to the country search view

---

conf/application.conf
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryBuilderSpec.scala

- inject the configuration object rather than the Play app
- escape quote in facets (fixes #572)
- map -> foreach where handling mutable request builder
- cleanup `application.conf`

Solr fixes

---

modules/core/test/resources/solrQueryResponse1.json
modules/solr/src/main/scala/eu/ehri/project/search/solr/JsonResponseHandler.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryParserSpec.scala

Fix parsing of array values from Solr data fields.

---

modules/portal/app/views/about.scala.html
modules/portal/conf/messages

Releasing this now in English - translation to come.

Update about text as per #608. 

---

modules/admin/app/controllers/keywords/Concepts.scala
modules/admin/app/views/admin/concept/adminActions.scala.html
modules/admin/app/views/admin/concept/description.scala.html
modules/admin/app/views/admin/concept/descriptionForm.scala.html
modules/admin/app/views/admin/concept/itemPage.scala.html
modules/admin/app/views/admin/concept/linkTo.scala.html
modules/admin/app/views/admin/link/linkSourceList.scala.html
modules/admin/app/views/admin/search/searchItemList.scala.html
modules/admin/app/views/admin/search/searchItemListWithAdditionalContent.scala.html
modules/admin/conf/keywords.routes
modules/admin/conf/messages
modules/core/app/global/GlobalConfig.scala
modules/core/app/models/Concept.scala
modules/core/app/models/ConceptDescription.scala
modules/portal/app/assets/css/admin.less
modules/portal/app/views/common/search/searchItemList.scala.html
modules/portal/conf/messages

- allow creating links between concepts
- import UI for selecting a link target
- add URL attribute
- display URL and lat/long
- show a small map if we have a lat/long
Closes #544

Linkable concepts

---

modules/guides/app/controllers/portal/guides/Assets.scala
modules/guides/app/views/guides/facet.scala.html
modules/guides/app/views/guides/places.scala.html
modules/guides/app/views/layout/guideLayout.scala.html
modules/guides/conf/guides.routes

Closes #632 
(thanks @PonteIneptique !)

Rename guide asset controller and fix incorrect guide js route references. 

---

modules/admin/app/controllers/admin/LegacyAccounts.scala
modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/controllers/users/UserProfiles.scala
modules/admin/app/views/admin/userProfile/search.scala.html
modules/admin/conf/messages
modules/admin/conf/users.routes
modules/portal/app/controllers/base/CsvHelpers.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
project/Build.scala
test/integration/EntityViewsSpec.scala

- update OpenCSV
- moved some common CSV code into a shared trait
- added export function and test
Closes #638

Add facility for admins to export a CSV of user info.

---

conf/application.conf
modules/backend/src/main/scala/backend/rest/Constants.scala
modules/backend/src/main/scala/backend/rest/RestDAO.scala
modules/backend/src/main/scala/utils/params.scala
modules/core/app/controllers/generic/Generic.scala
modules/portal/app/indexing/CmdlineIndexer.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
project/Build.scala

- Change user marker header name to `X-User`
- Change log message header name to `X-LogMessage`
- Minor additional cleanups

Support Neo4j basic auth and backend version 0.10.4-SNAPSHOT.

---

conf/application.conf
modules/admin/app/views/admin/documentaryUnit/create.scala.html
modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
modules/admin/app/views/admin/documentaryUnit/form.scala.html
modules/admin/app/views/admin/group/memberForm.scala.html
modules/admin/app/views/admin/historicalAgent/create.scala.html
modules/admin/app/views/admin/historicalAgent/descriptionForm.scala.html
modules/admin/app/views/admin/link/linkForm.scala.html
modules/admin/app/views/admin/metrics.scala.html
modules/admin/app/views/admin/permissions/visibilityForm.scala.html
modules/admin/app/views/admin/repository/form.scala.html
modules/admin/app/views/admin/search/updateIndex.scala.html
modules/admin/app/views/admin/userProfile/create.scala.html
modules/admin/app/views/formHelpers/accessPointSet.scala.html
modules/admin/app/views/formHelpers/inlineDateSet.scala.html
modules/admin/app/views/formHelpers/inlineName.scala.html
modules/admin/app/views/formHelpers/inlineNameSet.scala.html
modules/admin/app/views/formHelpers/submitButton.scala.html
modules/admin/app/views/formHelpers/submitButtonWithLogMessageInput.scala.html
modules/admin/conf/messages
modules/core/app/controllers/generic/Generic.scala
modules/core/app/global/GlobalConfig.scala
modules/core/app/models/PublicationStatus.scala
modules/portal/app/assets/css/admin/_admin.less
modules/portal/app/assets/css/admin/_forms.less
modules/portal/app/assets/css/ehri/_buttons.less

Fixed a bunch of inconsistencies and poor LESS style.
Fixes #643.

Limit size of log message to 400 chars. Lots of template cleanups.

---

modules/portal/app/assets/css/admin/_admin.less
modules/portal/app/assets/css/ehri/_descriptions.less
modules/portal/app/assets/css/portal/_feedback.less
modules/portal/app/assets/css/portal/_profile.less
modules/portal/app/views/layout/feedbackForm.scala.html

Additional small less refactorings.

Fix for dodgy footer css on feedback form.

---

modules/core/app/utils/search/FacetClass.scala
modules/portal/app/views/common/search/facetList.scala.html
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrFacetParser.scala
modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryBuilderSpec.scala
modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryParserSpec.scala

Also add options for minCount and limit to `FacetClass`.

Perform facet sorted on the server side rather than the client.

---

modules/backend/src/main/scala/backend/Generic.scala
modules/backend/src/main/scala/backend/rest/RestGeneric.scala
test/utils/search/MockSearchEngineConfig.scala

Compiler did not like overloaded list() methods with default params.

Fix small compilation issue on Scala 2.11.

---

modules/portal/app/controllers/portal/Vocabularies.scala
modules/portal/app/views/concept/childItemSearch.scala.html
modules/portal/app/views/concept/itemDetails.scala.html
modules/portal/app/views/concept/show.scala.html
modules/portal/app/views/vocabulary/itemDetails.scala.html

- remove superfluous char in template
- don't only show top-level items
- show sub items on portal concept view
Fixes #663

WIP Improve vocabulary concept list view on portal.

---

modules/core/app/controllers/base/AuthConfigImpl.scala
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/controllers/generic/Read.scala
modules/core/app/views/Helpers.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/base/PortalAuthConfigImpl.scala
modules/portal/app/controllers/portal/base/PortalController.scala
project/Build.scala

Update prettytime and various other dependencies as well.

Update to play2-auth 0.14.1.

---

.travis.yml
app/ErrorHandler.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/views/errors/genericError.scala.html
modules/portal/app/views/errors/pageNotFound.scala.html
modules/portal/conf/messages
modules/portal/conf/messages.de
modules/portal/conf/messages.fr
modules/portal/conf/messages.pl

This handles things like bad requests when route binding fails.
Also add more tests to the travis config.
Fixes #698.

Add a client error handler.

---

modules/admin/app/views/admin/layout/adminLayout.scala.html
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/global/GlobalConfig.scala
modules/portal/app/views/layout/infobar.scala.html
modules/portal/app/views/layout/portalLayout.scala.html
modules/portal/app/views/portal.scala.html
modules/portal/conf/messages

This uses the ?embed=true param and has the advantage of requiring minimal code changes elsewhere.

Add a very naive embed mode which hides some page chrome.

---

modules/portal/app/assets/css/ehri/_breadcrumb.less
modules/portal/app/assets/css/ehri/_footer.less
modules/portal/app/assets/css/ehri/_layouts.less
modules/portal/app/views/layout/footer.scala.html

In fullscreen mode this overrides the max-width given by the default bootstrap container.

CSS tweaks to reestablish a page max-width and remove superfluous padding

---

modules/portal/app/models/CypherQuery.scala
modules/portal/test/models/ResultFormatSpec.scala

Array values are pipe-delimited.

Allow Cypher queries converted to CSV to handle nested arrays.

---

modules/admin/app/assets/js/access-points.js

TODO: Work out how to test this JS stuff!

Fix incorrect JS action references

---

conf/logback-play-dev.xml
modules/portal/app/indexing/SearchToolsIndexMediator.scala
project/Build.scala

Relatedly, when data is reindexed, this should resolve the name sort ordering issue.

Update search indexer tools and add a better means of debugging indexer.

---

modules/admin/app/assets/js/access-points.js
modules/admin/app/views/admin/documentaryUnit/editAccessPoints.scala.html
modules/admin/conf/messages

- Removed the (apparently non-functional) paging controls
- Tweaked some JS
- Fix an issue where type filters were not applied

Attempt to clean up parts of the access point management interface

---

modules/admin/app/controllers/cypher/CypherQueries.scala
modules/admin/app/views/admin/cypherQueries/list.scala.html
modules/admin/app/views/admin/cypherQueries/resultTable.scala.html
modules/admin/app/views/admin/cypherQueries/results.scala.html
modules/admin/conf/messages
modules/portal/app/models/CypherQuery.scala

This makes it easier to share a specific query with someone on the team, and have them be able to comprehend it without pasting a CSV into Excel or something.

Add a better UI for viewing Cypher queries, along with their results.

---

modules/portal/app/views/dataPolicy.scala.html
modules/portal/app/views/terms.scala.html

Remove erroneous container wrapping terms/data policy pages.

---

modules/admin/app/controllers/admin/Home.scala
modules/admin/app/controllers/events/SystemEvents.scala
modules/admin/app/controllers/groups/Groups.scala
modules/admin/app/controllers/keywords/Concepts.scala
modules/admin/app/controllers/virtual/VirtualUnits.scala
modules/backend/src/main/scala/backend/DataApi.scala
modules/backend/src/main/scala/backend/rest/RestApi.scala
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/controllers/generic/AccessPoints.scala
modules/core/app/controllers/generic/ItemPermissions.scala
modules/core/app/controllers/generic/Linking.scala
modules/core/app/controllers/generic/PermissionHolder.scala
modules/core/app/controllers/generic/Read.scala
modules/core/app/controllers/generic/ScopePermissions.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/VirtualUnits.scala
modules/portal/app/controllers/portal/base/Generic.scala
modules/portal/app/controllers/portal/social/Social.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
modules/portal/app/views/portal.scala.html
test/backend/RestApiSpec.scala
test/integration/admin/EntityViewsSpec.scala
test/integration/admin/UserGroupPermissionSpec.scala
test/integration/portal/AnnotationsSpec.scala

Rename a few methods on the data API for better consistency.
Small tweak to main template layout.

Data api method refactor

---

project/Build.scala

Neglecting to update this dep seemed to cause major problems, since after the initial ClassNotFound error subsequent requests were served with 503s. Needs investigating...

Emergency update to Play Mailer.

---

.travis.yml
modules/portal/test/utils/mailer/MailerSpec.scala

Some funky travis config to set up a mock SMTP server.

Add a test that exercises the mailer

---

modules/core/app/models/Annotation.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/app/views/repository/description.scala.html
project/Build.scala
test/backend/RestApiSpec.scala

- update backend version
- small interface tweaks

Test patch with unsetting properties

---

modules/portal/app/assets/js/index_utils.js

Using onprogress event instead of nasty polling. The message parsing code is still gross and inefficient, but less buggy.
Since we can't use websockets :disappointed:

Make index progress output JS slightly less buggy and horrible.

---

modules/portal/app/assets/js/feedback.js

Add an error highlight on feedback email field if it is invalid.

---

modules/admin/app/views/admin/documentaryUnit/description.scala.html
modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
modules/admin/conf/messages
modules/core/app/models/DocumentaryUnitDescription.scala
modules/core/app/models/IsadG.scala
modules/core/test/resources/DocumentaryUnit.json
modules/portal/app/views/documentaryUnit/description.scala.html
modules/portal/conf/messages
modules/portal/conf/messages.de
modules/portal/conf/messages.fr
modules/portal/conf/messages.pl

This maps to EADs `separatedmaterial`.

Add support for separatedUnitsOfDescription field.

---

modules/backend/src/main/scala/backend/rest/Constants.scala
modules/backend/src/main/scala/utils/params.scala
modules/core/app/defines/binders/package.scala
modules/portal/app/assets/css/ehri/_search.less
modules/portal/app/assets/css/ehri/_timeline.less
modules/portal/app/backend/aws/S3FileStorage.scala
modules/portal/app/backend/parse/ParseService.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/social/Social.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
modules/portal/app/models/EventSummary.scala
modules/portal/app/views/activity/eventBody.scala.html
modules/portal/app/views/activity/eventItem.scala.html
modules/portal/app/views/activity/eventSubjects.scala.html
modules/portal/app/views/activity/eventSummary.scala.html
modules/portal/app/views/userProfile/show.scala.html
modules/portal/app/views/userProfile/userActivity.scala.html
modules/portal/conf/messages
modules/portal/conf/portal.routes
modules/portal/conf/profile.routes
modules/portal/conf/social.routes
modules/portal/public/robots.txt
project/Build.scala

- events which have multiple subjects now indicate this in their
summaries
- events have a permalink showing their subject list
- permalinks for aggregate event summaries is a time-range of the
user's activity list
Additionally: update AWS libs

Improvements to portal activity logs

---

modules/portal/app/controllers/portal/Countries.scala
modules/portal/app/controllers/portal/Repositories.scala
modules/portal/app/views/country/listItemBody.scala.html
modules/portal/app/views/repository/listItemBody.scala.html
project/plugins.sbt

- order by name by default
- remove search teaser text
Fixes #763 and #762.
Additionally, update to Play 2.5.3.

Tweak default sort and list display for countries and repositories

---

modules/admin/app/controllers/institutions/Repositories.scala
modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/core/app/utils/search/FacetClass.scala
modules/portal/app/assets/css/ehri/_search.less
modules/portal/app/assets/js/common.js
modules/portal/app/controllers/portal/FacetConfig.scala
modules/portal/app/views/common/search/facetList.scala.html

Also remove various other facets which are generally unused.
Some hard-coded strings could be translated ("more", "less").
Fixes #761

Add country and holder facets to institution/archival data page.

---

modules/admin/app/views/admin/authoritativeSet/show.scala.html
modules/admin/app/views/admin/concept/adminActions.scala.html
modules/admin/app/views/admin/country/adminActions.scala.html
modules/admin/app/views/admin/documentaryUnit/adminActions.scala.html
modules/admin/app/views/admin/historicalAgent/adminActions.scala.html
modules/admin/app/views/admin/repository/adminActions.scala.html
modules/admin/app/views/admin/virtualUnit/adminActions.scala.html
modules/admin/app/views/admin/vocabulary/show.scala.html
modules/admin/conf/messages
modules/portal/app/controllers/portal/Repositories.scala
modules/portal/conf/messages
project/Build.scala

- allow repos to export EAD with a format parameter (EAG is default)
- add an extra section for export formats to admin item pages

Changes to non-HTML data export (EAD/EAC/EAG/RDF etc)

---

modules/admin/app/controllers/sets/AuthoritativeSets.scala
modules/admin/app/views/admin/authoritativeSet/adminActions.scala.html
modules/admin/app/views/admin/authoritativeSet/show.scala.html
modules/admin/app/views/admin/country/adminActions.scala.html
modules/admin/conf/sets.routes
modules/portal/app/controllers/portal/Countries.scala
modules/portal/app/controllers/portal/DocumentaryUnits.scala
modules/portal/app/controllers/portal/HistoricalAgents.scala
modules/portal/app/controllers/portal/Repositories.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/conf/portal.routes
test/integration/portal/PortalSpec.scala

- Allow exporting auth set entries as zipped EAC
- Allow exporting country entries as zipped EAG
Refactor some export stuff to remove duplicate code.

Export improvements.

---

conf/routes
modules/apiv1/app/controllers/api/v1/ApiV1.scala
modules/apiv1/app/models/api/v1/JsonApiV1.scala
modules/apiv1/conf/apiv1.routes
modules/apiv1/conf/messages
modules/core/app/controllers/base/ControllerHelpers.scala
modules/core/app/defines/EnumerationBinders.scala
modules/portal/app/controllers/portal/account/Accounts.scala
project/Build.scala
test/helpers/TestConfiguration.scala
test/integration/api/v1/ApiV1QuickSpec.scala
test/integration/api/v1/ApiV1Spec.scala
test/resources/jsonapi-schema.json

Currently this only supports doc units, repos, authorities, and countries. The model data is also quite incomplete and in several cases simplified.
The following actions are supported:
- fetching items by ID
- searching all supported items
- searching inside items

First pass at implementing a jsonapi.org/ compatible versioned API

---

modules/apiv1/app/models/api/v1/JsonApiV1.scala

Add neglected authority name fields

---

modules/core/app/views/Highlighter.scala
modules/portal/app/views/concept/searchItem.scala.html
modules/portal/app/views/country/searchItem.scala.html
modules/portal/app/views/documentaryUnit/searchItem.scala.html
modules/portal/app/views/historicalAgent/searchItem.scala.html
modules/portal/app/views/repository/searchItem.scala.html
modules/portal/app/views/virtualUnit/searchItem.scala.html
modules/portal/app/views/vocabulary/searchItem.scala.html

Only pass a highlighter around when we don't need a search hit

---

modules/portal/app/views/concept/listItem.scala.html
modules/portal/app/views/concept/listItemBody.scala.html
modules/portal/app/views/concept/searchItem.scala.html
modules/portal/app/views/country/listItem.scala.html
modules/portal/app/views/country/listItemBody.scala.html
modules/portal/app/views/country/searchItem.scala.html
modules/portal/app/views/documentaryUnit/listItemBody.scala.html
modules/portal/app/views/documentaryUnit/searchItem.scala.html
modules/portal/app/views/helpers/link.scala.html
modules/portal/app/views/helpers/linkTo.scala.html
modules/portal/app/views/helpers/linkToWithFragment.scala.html
modules/portal/app/views/historicalAgent/listItem.scala.html
modules/portal/app/views/historicalAgent/searchItem.scala.html
modules/portal/app/views/repository/listItem.scala.html
modules/portal/app/views/repository/listItemBody.scala.html
modules/portal/app/views/repository/searchItem.scala.html
modules/portal/app/views/virtualUnit/infobar.scala.html
modules/portal/app/views/virtualUnit/listItemBody.scala.html
modules/portal/app/views/virtualUnit/listItemVc.scala.html
modules/portal/app/views/virtualUnit/searchItem.scala.html
modules/portal/app/views/vocabulary/listItem.scala.html
modules/portal/app/views/vocabulary/searchItem.scala.html

This better allows adding target="_top" when rendering in embed mode.

Consolidate rendering of item links.

---

modules/apiv1/app/models/api/v1/JsonApiV1.scala
modules/core/app/models/base/AnyModel.scala
modules/core/test/models/base/AnyModelSpec.scala
modules/portal/test/utils/i18n/I18nSpec.scala

Sort descriptions depending on the current language so the most appropriate one should be first.
Fix an i18n test bug.

Add more info to API

---

modules/apiv1/app/controllers/api/v1/ApiV1.scala
modules/core/app/models/SystemEvent.scala
test/integration/api/v1/ApiV1QuickSpec.scala
test/integration/api/v1/ApiV1Spec.scala

Also disable on-by-default authorization.

Fix event date format

---

modules/portal/app/assets/css/ehri/_descriptions.less
modules/portal/app/views/country/itemDetails.scala.html
modules/portal/conf/messages

Reverts EHRI/ehri-frontend#791
A needed file was missing.

Revert "Add some boilerplate for empty country reports"

---

build.sbt

Update data converter version and Jersey test deps.

---

modules/admin/app/views/admin/common/descriptionForm.scala.html
modules/admin/app/views/formHelpers/accessPoint.scala.html
modules/admin/app/views/formHelpers/hiddenMaintenanceEvent.scala.html
modules/admin/app/views/formHelpers/hiddenMaintenanceEventSet.scala.html
modules/core/app/models/AccessPoint.scala
modules/core/app/models/ConceptDescription.scala
modules/core/app/models/DocumentaryUnitDescription.scala
modules/core/app/models/HistoricalAgentDescription.scala
modules/core/app/models/MaintenanceEvent.scala
modules/core/app/models/RepositoryDescription.scala
modules/core/app/models/base/AnyModel.scala
modules/core/test/models/base/AnyModelSpec.scala
modules/core/test/resources/DocumentaryUnit.json
modules/core/test/resources/HistoricalAgent.json
modules/core/test/resources/Repository.json
test/integration/admin/EntityViewsSpec.scala

This paves the way to actually displaying their data in a useful manner.

Add a dedicated model for maintenance events.

---

modules/guides/app/controllers/portal/guides/Guides.scala
modules/portal/app/controllers/base/SearchVC.scala

Add parenthesis around nodes in match pattern.

Adjust queries for Cypher 3 compatibility

---

build.sbt
modules/backend/src/main/scala/backend/DataApi.scala
modules/backend/src/main/scala/backend/rest/RestApi.scala
modules/core/app/controllers/generic/Creator.scala
test/backend/RestApiSpec.scala

- update to Neo4j 3.0.4
- tweak to the WS API for creating child items
- tweak WS API for fetching user info and add tests

Updates for backend 0.13.5.

---

modules/apiv1/app/controllers/api/v1/ApiV1.scala
modules/apiv1/app/models/api/v1/JsonApiV1.scala
modules/backend/src/main/scala/defines/EnumUtils.scala
modules/core/app/models/base/Accessor.scala
modules/core/app/models/base/AnyModel.scala
modules/core/app/models/json/package.scala
modules/core/app/utils/search/Facet.scala
modules/core/app/utils/search/FacetClass.scala
modules/portal/app/client/json/package.scala

Superficial cleanup to some JSON marshalling/unmarshalling code.

---

build.sbt
project/plugins.sbt

- Play 2.5.6
- Mailer 5.0.0
- Commons IO
- Indexer tool

Update Play and various dependencies.

---

README.md
docs/install.md

The install docs still need to be updated.

Update some documentation

---

project/plugins.sbt

Update to Play 2.5.8

---

modules/apiv1/app/controllers/api/v1/ApiV1.scala
modules/apiv1/conf/apiv1.routes

This means it is included in the links for next/prev page.

Add type parameter to the API route definition.

---

modules/portal/app/assets/css/ehri/_descriptions.less
modules/portal/app/controllers/portal/Countries.scala
modules/portal/app/controllers/portal/DocumentaryUnits.scala
modules/portal/app/controllers/portal/HistoricalAgents.scala
modules/portal/app/controllers/portal/Repositories.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/app/views/common/exportItem.scala.html
modules/portal/app/views/common/panel.scala.html
modules/portal/app/views/documentaryUnit/itemDetails.scala.html
modules/portal/app/views/historicalAgent/itemDetails.scala.html
modules/portal/app/views/repository/itemDetails.scala.html
modules/portal/conf/messages
modules/portal/conf/portal.routes
modules/portal/public/robots.txt

As EAD, EAG, and EAC respectively.

Add links on doc, repo, and authority pages to allow exporting items.

---

modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/views/admin/regenerateIdsForm.scala.html

Put the increased timeout in the right place and improve the output table a bit.

Improvements to ID regenerator.

---

modules/portal/app/controllers/portal/Portal.scala

Also ensure they are fetched anonymously, which wasn't previously the case.

Reinstate caching of stats, since it does make a difference.

---

modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/views/admin/movedItemsForm.scala.html
test/integration/admin/UtilsSpec.scala

- Handle reindexing when adding moved pages via CSV
- Switch from TSV to CSV

Refactor moved item utils a bit.

---

build.sbt
modules/backend/src/main/scala/backend/rest/RestError.scala
modules/backend/src/main/scala/backend/rest/RestService.scala

Update backend version, for slightly more consistent error handling.

---

modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/views/admin/regenerate.scala.html
modules/admin/app/views/admin/regenerateIds.scala.html
modules/admin/app/views/admin/regenerateIdsForm.scala.html
modules/admin/conf/admin.routes
modules/backend/src/main/scala/backend/DataApi.scala
modules/backend/src/main/scala/backend/rest/RestApi.scala
modules/backend/src/main/scala/defines/binders/package.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala

This is mostly busywork, but it seems like to come up enough that a half-decent UI is worth it.

More development of the ID-regeneration UI.

---

modules/api/app/controllers/api/v1/ApiV1.scala
modules/core/app/auth/oauth2/WebOAuth2Flow.scala
modules/core/app/controllers/base/ControllerHelpers.scala
modules/core/app/controllers/base/RecaptchaHelper.scala
modules/core/app/controllers/core/auth/oauth2/OAuth2LoginHandler.scala
modules/core/app/controllers/core/auth/openid/OpenIDLoginHandler.scala
modules/core/app/controllers/core/auth/userpass/UserPasswordLoginHandler.scala
modules/core/app/controllers/generic/Read.scala
modules/core/app/controllers/generic/Search.scala
modules/core/app/global/GlobalEventHandler.scala
modules/core/app/utils/forms/HoneyPotForm.scala
modules/core/app/utils/forms/TimeCheckForm.scala
modules/portal/app/client/json/package.scala
modules/portal/app/controllers/base/SearchVC.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/app/views/PegDownMarkdownRenderer.scala
modules/portal/test/views/PegDownMarkdownProcessorSpec.scala

- timecheck/honeypot violation (now warnings)
- markdown parse timeout (now warning)

Prevent some error logging in spurious or unavoidable cases.

---

build.sbt
modules/backend/src/main/scala/backend/rest/RestApi.scala
modules/backend/src/main/scala/backend/rest/RestService.scala
modules/backend/src/main/scala/utils/http/package.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/QueryBuilder.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrFacetParser.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryBuilderSpec.scala

That library wasn't that useful, and in any case in unmaintained.
Other refactoring of search and some http utils.
Fixes #887

Refactor Solr query builder to not rely on Scalikesolr.

---

modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala

Add highlighting field list parameter.

---

modules/core/app/controllers/core/auth/oauth2/OAuth2LoginHandler.scala
modules/core/app/controllers/core/auth/openid/OpenIDLoginHandler.scala
modules/portal/conf/messages
test/integration/portal/AccountsSpec.scala

Show a better error for OAuth session ID problems.

---

conf/test.conf
modules/admin/app/controllers/cypher/CypherQueries.scala
modules/admin/app/views/admin/cypherQueries/list.scala.html
modules/admin/conf/cypher.routes
modules/admin/conf/messages
modules/portal/app/backend/sql/SqlCypherQueryService.scala
modules/portal/app/models/CypherQuery.scala
modules/portal/app/utils/SqlMovedPageLookup.scala
modules/portal/app/views/common/listSorting.scala.html
modules/portal/app/views/common/search/searchBar.scala.html
modules/portal/app/views/common/search/searchSort.scala.html
test/backend/sql/SqlCypherQueryServiceSpec.scala

- switch H2 compat mode to PostgreSQL and update places where this
breaks things
- refactor some search templates for non-Solr use

Allow filtering/sorting cypher queries.

---

build.sbt
modules/admin/conf/messages
modules/core/app/utils/Data.scala
modules/core/app/utils/i18n/package.scala
modules/core/test/utils/search/FacetSpec.scala
modules/portal/app/backend/CypherQueryService.scala
modules/portal/app/views/historicalAgent/description.scala.html
modules/portal/conf/messages

- Handle display of "sh" language: dufunct Serbo-Croatian
- Display otherFormsOfName for authorities

Small display fixes:

---

modules/admin/app/views/admin/concept/description.scala.html
modules/admin/app/views/admin/concept/descriptionForm.scala.html
modules/admin/app/views/admin/concept/form.scala.html
modules/core/app/models/Concept.scala
modules/core/app/models/ConceptDescription.scala
modules/guides/app/controllers/portal/guides/Guides.scala
modules/guides/app/views/guides/places.scala.html
modules/portal/app/views/concept/description.scala.html
modules/portal/conf/messages

Also:
- add better validation to various URI properties
- add hiddenLabel field
- tweak some UI

Move non-language-specific properties from concept description to item.

---

build.sbt

Add launcher jar plugin and other minor build formatting tweaks.

---

modules/admin/app/controllers/admin/Home.scala
modules/admin/app/controllers/authorities/HistoricalAgents.scala
modules/admin/app/controllers/countries/Countries.scala
modules/admin/app/controllers/institutions/Repositories.scala
modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/admin/app/views/admin/index.scala.html
modules/admin/conf/messages
modules/core/app/controllers/base/SessionPreferences.scala
modules/portal/app/utils/SessionPrefs.scala
test/integration/admin/DocumentaryUnitViewsSpec.scala

Items are saved in user session.

Display recently-visited items (for some types) on the admin home.

---

modules/portal/app/controllers/portal/base/PortalController.scala

URL encode id for use in content-disposition header

---

modules/portal/app/assets/css/_ehri-vars.less
modules/portal/app/assets/css/ehri/_search.less
modules/portal/app/assets/js/common.js
modules/portal/app/views/concept/inlineListItem.scala.html
modules/portal/app/views/concept/listItemBody.scala.html
modules/portal/app/views/country/listItemBody.scala.html
modules/portal/app/views/documentaryUnit/inlineListItem.scala.html
modules/portal/app/views/documentaryUnit/listItemBody.scala.html
modules/portal/app/views/repository/inlineListItem.scala.html
modules/portal/app/views/repository/listItemBody.scala.html
modules/portal/app/views/vocabulary/listItemBody.scala.html

This avoids problems with font-awesome, but is uglier.

Render search dropdown icons with their own element.

---

modules/admin/app/controllers/users/UserProfiles.scala
modules/admin/app/views/admin/userProfile/form.scala.html
modules/admin/app/views/admin/userProfile/itemPage.scala.html
modules/admin/app/views/admin/userProfile/listItem.scala.html
modules/admin/app/views/admin/userProfile/statusBadges.scala.html
modules/admin/conf/messages
modules/core/app/models/AdminUserData.scala
modules/core/app/services/accounts/SqlAccountManager.scala
test/integration/admin/EntityViewsSpec.scala

This is useful when they can't recieve the email for some reason.

Allow verifying users from the admin.

---

build.sbt
modules/admin/app/controllers/admin/Metrics.scala
modules/guides/app/controllers/portal/guides/Guides.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/PortalData.scala
project/build.properties
project/plugins.sbt

Also tidy up some cache durations.

Update Play, reconfigure a few dependencies, and make compiler happy.

---

modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/models/admin/BatchDeleteTask.scala
modules/admin/app/views/admin/Helpers.scala
modules/admin/app/views/admin/tools/batchDelete.scala.html
modules/admin/conf/admin.routes
modules/admin/conf/messages
modules/backend/src/main/scala/services/data/DataApi.scala
modules/backend/src/main/scala/services/data/DataApiService.scala
test/integration/admin/UtilsSpec.scala

e.g. links that are no longer needed.

Add a new admin util for deleting a batch of items.

---

modules/admin/app/views/admin/common/propertyList.scala.html
modules/admin/app/views/admin/repository/listItem.scala.html

Fix display of concept scope note on the admin pages

---

modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/social/Social.scala
modules/portal/app/views/account/mail/confirmEmail.scala.txt
modules/portal/app/views/account/mail/forgotPassword.scala.txt
modules/portal/app/views/account/resetPassword.scala.html
modules/portal/app/views/social/mail/messageEmail.scala.txt
modules/portal/conf/messages
test/integration/admin/ApplicationSpec.scala
test/integration/portal/SignupSpec.scala

- only send plain text
- add user's name to recipient email address
Some small other tweaks to templates

Try and prevent pw reset emails getting blocked so often

---

build.sbt
modules/portal/app/services/storage/S3FileStorage.scala
project/plugins.sbt

- Play
- Alpakka
- Anorm
- Mailer

Update various components:

---

modules/admin/app/views/admin/Helpers.scala
modules/admin/conf/messages

Add a menu item for adding ID redirects

---

modules/core/app/services/search/FacetClass.scala
modules/portal/app/assets/css/ehri/_facets.less
modules/portal/app/assets/css/ehri/_panels.less
modules/portal/app/assets/css/ehri/_search.less
modules/portal/app/assets/css/portal.less
modules/portal/app/controllers/portal/FacetConfig.scala
modules/portal/app/views/common/search/facetList.scala.html
modules/portal/app/views/common/search/searchForm.scala.html
modules/portal/conf/messages

- restyle CSS to look better
- make all facets exclusive
- tweak text
- remove 'hard to understand' facets

Minor rework of facets

---

conf/form-defaults.conf
modules/admin/app/views/admin/concept/descriptionForm.scala.html
modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
modules/admin/app/views/admin/documentaryUnit/form.scala.html
modules/admin/app/views/admin/historicalAgent/create.scala.html
modules/admin/app/views/admin/historicalAgent/descriptionForm.scala.html
modules/admin/app/views/admin/historicalAgent/edit.scala.html
modules/admin/app/views/admin/historicalAgent/form.scala.html
modules/admin/app/views/admin/link/linkForm.scala.html
modules/admin/app/views/admin/repository/addressForm.scala.html
modules/admin/app/views/admin/repository/descriptionForm.scala.html
modules/admin/app/views/admin/repository/form.scala.html
modules/admin/app/views/admin/tools/findReplace.scala.html
modules/admin/app/views/formHelpers/choiceInput.scala.html
modules/admin/app/views/formHelpers/enumChoiceInput.scala.html
modules/admin/conf/messages
modules/core/app/models/DocumentaryUnit.scala
modules/guides/app/views/admin/guide/create.scala.html
modules/guides/app/views/admin/guide/delete.scala.html
modules/guides/app/views/admin/guide/edit.scala.html
modules/guides/app/views/admin/guide/show.scala.html
modules/guides/app/views/admin/guidePage/create.scala.html
modules/guides/app/views/admin/guidePage/delete.scala.html
modules/guides/app/views/admin/guidePage/edit.scala.html
modules/guides/app/views/admin/guidePage/renderForm.scala.html
modules/guides/app/views/admin/layout/guidesAdminLayout.scala.html

This allows choice inputs to handle form defaults.

Refactor some form helpers and tweak some templates.

---

app/ErrorHandler.scala
modules/api/app/controllers/api/v1/ApiV1.scala
modules/api/app/models/api/v1/JsonApiV1.scala
modules/api/app/views/api/v1/docs.scala.html
modules/api/conf/api.routes
modules/api/conf/messages
modules/backend/src/main/scala/utils/params.scala
modules/core/app/services/search/Facet.scala
modules/core/app/services/search/SearchParams.scala
modules/core/app/utils/binders/package.scala
modules/core/test/utils/binders/BindersSpec.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
test/integration/api/v1/ApiV1Spec.scala

- Added bounding box search
- Added geo data to search API responses
- Implement sparse fieldsets for search API

Search and API enhancements

---

modules/admin/app/views/admin/common/dateSet.scala.html
modules/core/app/models/DatePeriod.scala
modules/core/test/models/DatePeriodSpec.scala
modules/portal/app/views/documentaryUnit/details.scala.html

This should no longer just truncate them to the year.

Add some (horrible) code to format date periods in a better manner

---

modules/admin/app/assets/js/access-points.js
modules/admin/app/views/admin/common/accessPointForm.scala.html

The backend would reject these, but it would cause an Ajax error

Prevent submission of access points with invalid info (e.g. no name)

---

modules/backend/src/main/scala/utils/streams/JsonStream.scala
modules/backend/src/test/scala/utils/streams/JsonStreamSpec.scala

Fix the behaviour of the JSON stream parser WRT empty objects.

---

conf/application.conf
modules/admin/app/controllers/admin/Ingest.scala
modules/admin/app/controllers/admin/Tasks.scala
modules/admin/app/controllers/countries/Countries.scala
modules/admin/app/views/admin/tasks/taskMonitor.scala.html
modules/admin/conf/admin.routes
modules/admin/conf/countries.routes
modules/admin/conf/messages
modules/core/app/models/Address.scala
modules/portal/app/global/GeocodingItemLifecycle.scala
modules/portal/app/services/geocoding/BingGeocodingService.scala
test/integration/admin/IngestSpec.scala

Not for general use at the moment, hence no link to the page.

Add minimal UI for geocoding all repositories in a given country

---

app/ErrorHandler.scala
modules/admin/app/controllers/admin/Utils.scala
modules/admin/app/views/admin/Helpers.scala
modules/admin/app/views/admin/tools/redirectForm.scala.html
modules/admin/app/views/formHelpers/fieldTemplate.scala.html
modules/admin/conf/admin.routes
modules/admin/conf/messages
test/integration/admin/UtilsSpec.scala
test/integration/portal/PortalSpec.scala

Also add a redirect check in the global 404 handler.

Add a tool to create a page redirect from one path to another

---

app/ErrorHandler.scala
build.sbt
modules/backend/src/main/scala/utils/http/package.scala
modules/backend/src/test/scala/utils/http/HttpSpec.scala
modules/portal/app/controllers/portal/base/PortalController.scala

Unfortunate to have to use an external dependency for this. In the future maybe rewrite the method to not use Jena.
Fixes #1054

Convert IRIs to URIs before redirecting.

---

modules/api/app/controllers/api/v1/ApiV1.scala
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/controllers/base/SessionPreferences.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/base/PortalController.scala

Also, hope to avoid a double-redirect on login.

Refactor some session-related methods to make intent clearer.

---

modules/portal/app/views/dataPolicy.scala.html
modules/portal/app/views/dataPolicyModal.scala.html
modules/portal/conf/messages
modules/portal/conf/messages.de
modules/portal/conf/messages.fr
modules/portal/conf/messages.pl

Translations commented out till we can re-translate.)

Update EHRI data policy and terms/conditions

---

app/ErrorHandler.scala
modules/backend/src/main/scala/services/data/DataApiError.scala
project/plugins.sbt

Prevent JSON errors being swallowed by Akka HTTP

---

build.sbt

This fixes excluded resources not being excluded.

Ensure the main SBT project uses the web app settings.

---

conf/form-config.conf
modules/admin/app/models/forms/FormConfig.scala
modules/admin/app/views/admin/Helpers.scala
modules/admin/app/views/admin/common/descriptionForm.scala.html
modules/admin/app/views/admin/concept/descriptionForm.scala.html
modules/admin/app/views/admin/concept/form.scala.html
modules/admin/app/views/admin/documentaryUnit/createDescription.scala.html
modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
modules/admin/app/views/admin/documentaryUnit/editDescription.scala.html
modules/admin/app/views/admin/documentaryUnit/form.scala.html
modules/admin/app/views/admin/historicalAgent/descriptionForm.scala.html
modules/admin/app/views/admin/historicalAgent/form.scala.html
modules/admin/app/views/admin/link/linkForm.scala.html
modules/admin/app/views/admin/repository/addressForm.scala.html
modules/admin/app/views/admin/repository/descriptionForm.scala.html
modules/admin/app/views/admin/repository/form.scala.html
modules/admin/app/views/admin/tools/findReplace.scala.html
modules/admin/app/views/admin/tools/regenerateForm.scala.html
modules/admin/app/views/admin/virtualUnit/createDescription.scala.html
modules/admin/app/views/admin/virtualUnit/editDescription.scala.html
modules/admin/app/views/admin/virtualUnit/form.scala.html
modules/admin/app/views/formHelpers/choiceInput.scala.html
modules/admin/app/views/formHelpers/enumChoiceInput.scala.html
modules/admin/app/views/formHelpers/fieldTemplate.scala.html
modules/admin/app/views/formHelpers/lineInput.scala.html
modules/admin/app/views/formHelpers/textInput.scala.html
modules/portal/app/views/Helpers.scala
test/integration/admin/EntityViewsSpec.scala

It's now possible to add form hints, changes the number of text area
rows, set fields required, and hide fields from form config.

More refactoring of forms for more flexible configuration.

---

README.md
conf/aws.conf.example
modules/portal/app/services/storage/S3FileStorage.scala

Also tweak the S3 file storage so it doesn't crash at provisioning time.

Add a couple of notes to the README about postfix/aws dependencies

---

modules/portal/app/controllers/portal/Portal.scala

Fix a crash when attempting to set the language w/ an invalid code

---

modules/portal/app/assets/css/_ehri-vars.less
modules/portal/app/assets/css/ehri/_facets.less
modules/portal/app/assets/css/ehri/_layouts.less
modules/portal/app/assets/css/ehri/_search.less
modules/portal/app/assets/css/ehri/_searchbar.less
modules/portal/app/views/common/search/facetList.scala.html
modules/portal/app/views/common/topNavBar.scala.html

Change size at which sidebars collapse (from md to sm) - this is just to make the sidebar nav collapse match the toolbar collapse and is a bit of a hack.

Make facets act like a collabsible navbar.

---

modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala

Not sure why we didn't use fq in the first place...
This should fix an issue with the access point editor where nothing was found due to the new AND behaviour of the q field.

Use fq for arbitrary filters instead of the q param

---

conf/application.conf
modules/portal/app/controllers/portal/Feedback.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/app/controllers/portal/social/Social.scala

And avoid hardcoding noreply as an address

Make more email addresses configurable for bookkeeping emails

---

modules/portal/app/views/account/login.scala.html
modules/portal/app/views/account/loginForm.scala.html
modules/portal/app/views/account/oauth2Form.scala.html
modules/portal/app/views/account/signupForm.scala.html
modules/portal/app/views/common/preambleScripts.scala.html

Also fix dup DOM ids and remove i18n script for select2 JS

Add some autocomplete attrs to login/signup forms

---

modules/guides/app/assets/js/portal-guide.js
modules/guides/app/views/guides/facet.scala.html

This is still a bit broken because search doesn't work when a facet is selected, for some reason.

Partially fix guide search after select2 update.

---

modules/guides/app/assets/css/guides.scss
modules/guides/app/assets/css/guides/_variables.scss
modules/guides/app/controllers/portal/guides/Guides.scala
modules/guides/app/views/guides/facet.scala.html
modules/guides/app/views/guides/person.scala.html
modules/guides/app/views/guides/repository.scala.html
modules/guides/app/views/layout/guideLayout.scala.html

Also prevent double-bundling of the portal CSS.

Fix some of the most broken parts of the guides layout.

---

modules/core/app/models/DatePeriod.scala

Prevent String out of bounds exception formatting dates

---

modules/admin/app/assets/css/admin.scss
modules/admin/app/assets/css/admin/_accesspoints.scss
modules/admin/app/assets/css/admin/_admin.scss
modules/admin/app/assets/css/vocabeditor.scss
modules/admin/app/assets/js/vocabeditor.js
modules/admin/app/client/json/package.scala
modules/admin/app/controllers/keywords/Concepts.scala
modules/admin/app/controllers/vocabularies/VocabularyEditor.scala
modules/admin/app/views/admin/common/testWarning.scala.html
modules/admin/app/views/admin/layout/adminLayout.scala.html
modules/admin/app/views/admin/vocabulary/adminActions.scala.html
modules/admin/app/views/admin/vocabulary/vocabeditor.scala.html
modules/admin/conf/messages
modules/admin/conf/vocabularies.routes
modules/backend/src/main/scala/services/data/DataApi.scala
modules/backend/src/main/scala/services/data/DataApiService.scala
modules/backend/src/main/scala/services/data/EventHandler.scala
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/core/app/global/GlobalEventHandler.scala
modules/core/app/models/json/package.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
test/helpers/TestConfiguration.scala
test/integration/admin/VocabularyEditorSpec.scala

Other changes:
- made event handlers accept a list of IDs so search engine updates can be batched if necessary
- some tweaks to data API methods

Add a dedicated VueJS editor for vocabulary concepts

---

modules/admin/app/assets/css/vocabeditor.scss
modules/admin/app/assets/js/vocabeditor.js
modules/admin/app/controllers/vocabularies/VocabularyEditor.scala
modules/admin/app/views/admin/vocabulary/vocabeditor.scala.html
modules/admin/conf/vocabularies.routes
test/integration/admin/VocabularyEditorSpec.scala

This has the same caveats as usual, namely it might collide or re-use previously deleted IDs.
Also add some extra metadata for last updated date.

Try and create a numeric identifier for new concepts.

---

modules/admin/app/assets/css/vocabeditor.scss
modules/admin/app/assets/js/vocabeditor.js
modules/admin/app/controllers/vocabularies/VocabularyEditor.scala

Also fix response type of serverside creation error.

Better error handling and form field highlighting.

---

modules/portal/app/assets/js/lib/leaflet.curve.js
modules/portal/app/controllers/portal/Links.scala
modules/portal/app/views/link/copies.scala.html
modules/portal/conf/portal.routes

This isn't final UI (hence not linked from anywhere) but serves as a map example to hopefully spur further development.

Quick demo leaflet map showing copy-links between repositories.

---

modules/portal/app/views/link/copies.scala.html

Hopefully this will look less busy...

Tweak map a bit

---

build.sbt

This caused the server to crash.

Fix No Method Error caused by Akka HTTP binary incompatibility.

---

app/ErrorHandler.scala
modules/core/app/auth/handler/cookie/CookieAuthHandler.scala
modules/core/app/controllers/base/CoreActionBuilders.scala
modules/portal/app/controllers/portal/base/PortalController.scala

This means that error pages no longer have to omit any login info etc. Some additional refactoring of functions in the action builders.
Related to #1173

Allow fetching/supplying user context in error pages.

---

modules/api/app/controllers/api/v1/ApiV1.scala

This makes the API match the regular page behaviours. Technically
it's a breaking change but we're not going to tell anyone.

Make full-search searching dependent on whether there's a query

---

build.sbt
modules/admin/app/views/formHelpers/fieldTemplate.scala.html
modules/portal/app/views/helpers/fieldTemplateHorizontal.scala.html
project/plugins.sbt

Also some satisfying the compiler for mysterious reasons.

Update Play and Scala version.

---

modules/api/app/views/api/datasets/datasets.scala.html
modules/api/app/views/api/docs.scala.html
modules/api/app/views/api/layout/apiDocLayout.scala.html
modules/api/app/views/api/oaipmh/docs.scala.html
modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/views/common/searchItemOutlineWithActions.scala.html

The dataset list was particularly broken.

Improve markup on API sidebar navigations and styling of datasets

---

modules/admin/app/views/admin/group/show.scala.html
modules/admin/app/views/admin/userProfile/listItem.scala.html
modules/admin/app/views/admin/userProfile/show.scala.html
modules/admin/conf/messages

Also fix erroneous toString on group template

Make some small improvements to info show on admin user pages

---

modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/views/index.scala.html

- add title to video iframe
- increase text contrast on blog entry dates

Fix a couple of minor accessibility issues on the front page.

---

modules/admin/app/views/admin/concept/show.scala.html
modules/admin/app/views/admin/cypherQueries/resultTable.scala.html
modules/admin/app/views/admin/repository/description.scala.html
modules/portal/app/utils/markdown/CommonmarkMarkdownRenderer.scala
modules/portal/app/utils/markdown/FlexmarkMarkdownRenderer.scala
modules/portal/app/utils/markdown/SanitisingMarkdownRenderer.scala
modules/portal/app/views/account/signupForm.scala.html
modules/portal/app/views/common/footer.scala.html
modules/portal/app/views/common/markdownCheatsheet.scala.html
modules/portal/app/views/dataPolicy.scala.html
modules/portal/app/views/errors/pageNotFound.scala.html
modules/portal/app/views/repository/description.scala.html
modules/portal/app/views/userProfile/details.scala.html
modules/portal/test/utils/markdown/CommonmarkMarkdownRendererSpec.scala
modules/portal/test/utils/markdown/FlexmarkMarkdownRendererSpec.scala

Add rel=noopener to links that open in a _blank window.

---

modules/portal/app/views/common/accountHeaderRightMenu.scala.html
modules/portal/conf/messages

Added noopener attribute to manual link and aria-hidden to profile icon

More small fixes to the account menu

---

build.sbt
conf/application.conf
modules/portal/app/controllers/portal/Feedback.scala

Now send one mail with multiple recipients instead of multiple mails

Update Play Mailer and add slightly more debug to feedback mails

---

conf/application.conf
modules/core/app/global/GlobalConfig.scala
modules/portal/app/controllers/portal/Feedback.scala
modules/portal/app/views/common/accountHeader.scala.html
modules/portal/app/views/common/accountHeaderRightMenu.scala.html
modules/portal/app/views/index.scala.html
modules/portal/app/views/layout/errorLayout.scala.html
modules/portal/app/views/layout/portalLayout.scala.html
modules/portal/app/views/layout/portalLayoutSimple.scala.html
modules/portal/conf/messages

Ultimately it might be best to strip it out altogether.

Make the feedback submission system toggleable via an option.

---

build.sbt
fabfile.py
project/plugins.sbt

Also tweak fabfile is we can build and deploy with openjdk

Update to Play 2.8.1

---

modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/assets/css/portal/_variables.scss
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/base/PortalController.scala

Also make a missing external page or feed show a page not found rather than an item not found 404 message.

Tweak some CSS for heading sizes (esp. in external pages)

---

modules/api/app/views/api/v1/docs.scala.html
modules/core/app/services/search/SearchParams.scala
modules/core/app/utils/binders/package.scala
modules/core/test/utils/binders/BindersSpec.scala
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala

Also fix a bug where specifying location sort on its own would crash Solr.

Add a latlng parameter to the search params for distance sort.

---

app/Module.scala
modules/core/app/auth/oauth2/providers/OAuth2Provider.scala
modules/core/app/services/oauth2/OAuth2Service.scala
modules/core/app/services/oauth2/WebOAuth2Service.scala
modules/portal/app/auth/oauth2/providers/YahooOAuth2Provider.scala
modules/portal/app/controllers/portal/account/Accounts.scala
modules/portal/test/auth/oauth2/MockOAuth2Service.scala
modules/portal/test/auth/oauth2/providers/YahooOAuth2ProviderSpec.scala
modules/portal/test/resources/yahooUserData.txt
test/helpers/TestConfiguration.scala

Also refactor the OAuth2 services classes for consistency.

Clean up previous commit and fix tests.

---

modules/admin/app/views/admin/virtualUnit/descriptionActions.scala.html
modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/views/common/accountHeaderRightMenu.scala.html
modules/portal/app/views/common/descriptionSwitcher.scala.html

This reverts back to a more default bootstrap scheme instead of the slightly obtuse system used before.

Rationalise CSS for dropdown menus.

---

build.sbt
project/plugins.sbt
test/helpers/TestConfiguration.scala
test/integration/admin/IngestSpec.scala
test/integration/admin/SearchSpec.scala
test/services/data/DataApiServiceSpec.scala

Also: use Play's refs to Akka/Akka HTTP versions and add hacks to get around router initialization issues.

Update Play to 2.8.4

---

modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/views/account/loginForm.scala.html
modules/portal/app/views/account/signupForm.scala.html
modules/portal/app/views/common/accountHeaderRightMenu.scala.html
modules/portal/app/views/helpers/fieldTemplateSignUp.scala.html
modules/portal/app/views/index.scala.html

- increase contrast on minor text items in footer and sort menu
- add hidden (sr_only) labels to login/signup inputs
- add role="menuitem" to some dropdown items

Fix some accessibility issues revealed by WAVE

---

modules/api/app/views/api/graphql/docs.scala.html

Remove warning from GraphQL docs.

---

conf/evolutions/default/1.sql
modules/admin/app/controllers/tools/Tools.scala
modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/admin/app/services/ingest/ImportLogService.scala
modules/admin/app/services/ingest/SqlImportLogService.scala
modules/admin/app/views/admin/documentaryUnit/rename.scala.html
modules/admin/conf/messages
modules/backend/src/main/scala/services/data/DataApi.scala
modules/backend/src/main/scala/services/data/DataApiService.scala
test/integration/admin/DocumentaryUnitViewsSpec.scala
test/services/ingest/SqlImportLogServiceSpec.scala

- rename import log refs when items change
- clear index on batch delete
Also add some more indexes on queried fields on import tables

Import more renaming and bulk deletion scenarios

---

.circleci/config.yml

This might need some tweaking.

Add a CircleCI config

---

modules/admin/app/views/admin/repository/create.scala.html
modules/admin/app/views/admin/repository/show.scala.html

Now switched to using the readonly attribute.
Also fixed the priority badge not being styled and missing messages.

Using a disabled attr for repository identifiers broke serialization

---

modules/admin/app/controllers/admin/AdminSearch.scala
modules/admin/app/controllers/institutions/Repositories.scala
modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/admin/app/controllers/virtual/VirtualUnits.scala
modules/admin/app/views/admin/documentaryUnit/inlineListItem.scala.html
modules/admin/app/views/admin/helpers/linkTo.scala.html
modules/admin/app/views/admin/helpers/linkToWithBody.scala.html
modules/admin/app/views/admin/helpers/linkToWithFragment.scala.html
modules/admin/app/views/admin/repository/inlineListItem.scala.html
modules/admin/app/views/admin/repository/listItem.scala.html
modules/admin/app/views/admin/search/inlineItemList.scala.html
modules/admin/app/views/admin/virtualUnit/inlineListItem.scala.html
modules/admin/app/views/admin/virtualUnit/listItemBody.scala.html
modules/admin/app/views/admin/virtualUnit/searchItemBody.scala.html
modules/portal/app/assets/js/common.js

This, as usual, involves a depressing amount of duplicating templates.

Implement inline list display of child for institutions and units

---

modules/portal/app/services/search/AkkaStreamsIndexMediator.scala

Put a bit more debug in the Akka streams indexer

---

app/Module.scala
modules/admin/app/views/admin/authoritativeSet/create.scala.html
modules/admin/app/views/admin/concept/form.scala.html
modules/admin/app/views/admin/country/create.scala.html
modules/admin/app/views/admin/documentaryUnit/create.scala.html
modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
modules/admin/app/views/admin/group/form.scala.html
modules/admin/app/views/admin/historicalAgent/form.scala.html
modules/admin/app/views/admin/virtualUnit/form.scala.html
modules/admin/app/views/admin/vocabulary/create.scala.html
modules/admin/app/views/formHelpers/fieldTemplate.scala.html
modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/services/search/AkkaStreamsIndexMediator.scala
modules/portal/conf/messages

We're getting the wrong GIDs after deletion for some reason... this is a stopgap fix.

Disabled the GID index mediator, plus some admin form tweaks.

---

modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/admin/app/views/admin/documentaryUnit/delete.scala.html
modules/admin/conf/messages
modules/admin/conf/units.routes
test/integration/admin/DocumentaryUnitViewsSpec.scala

Prevent parent items being deleted until their children are deleted first.

Stopgap measure to prevent orphaned items

---

modules/admin/app/controllers/countries/Countries.scala
modules/admin/app/views/admin/country/create.scala.html
modules/admin/app/views/admin/country/searchItem.scala.html

Improvements to the admin country UI

Country inlines

---

modules/admin/app/actors/transformation/XmlConverter.scala
modules/admin/app/assets/js/components/convert-manager.js
modules/admin/app/assets/js/components/ingest-manager.js
modules/admin/app/assets/js/datamanager.js
modules/admin/app/controllers/institutions/DataTransformations.scala
modules/admin/app/controllers/institutions/ImportDatasets.scala
modules/admin/app/controllers/institutions/OaiPmhConfigs.scala
modules/admin/app/controllers/institutions/ResourceSyncConfigs.scala
modules/admin/app/models/ImportDataset.scala
modules/admin/app/services/datasets/SqlImportDatasetService.scala
modules/admin/app/views/admin/repository/datamanager.scala.html
modules/admin/conf/ehri_ead.rng
modules/admin/conf/institutions.routes
modules/admin/test/resources/invalid-ead.xml
modules/admin/test/services/ingest/RelaxNGEadValidatorSpec.scala
test/helpers/package.scala
test/integration/admin/ImportDatasetsSpec.scala
test/integration/admin/ImportFilesSpec.scala
test/resources/import-dataset-fixtures.sql

Also tighten up a serialization in some places and start adding more testing for data API.
Additionally, changed the /delete endpoints to return 204 instead of 200.

Fix issue w/ saving datasets caused by null/missing value

---

conf/evolutions/default/1.sql

This happened if there were harvest events.

Don't error due to null constraint when deleting DS

---

conf/application.conf
modules/admin/app/controllers/institutions/DataTransformations.scala
modules/admin/app/services/transformation/WrappingXmlTransformer.scala
modules/api/app/controllers/api/v1/ApiV1.scala
modules/backend/src/main/scala/services/data/DataApiService.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/account/Accounts.scala
test/integration/admin/ApplicationSpec.scala

This would explain some memory issues we've had in production! Especially the caching of item JSON with no expiration! Also clean up some other caching durations.

Ensure that nothing is cached indefinitly.

---

modules/admin/app/controllers/links/Links.scala
modules/guides/app/controllers/portal/guides/Guides.scala
modules/portal/app/controllers/base/SearchVC.scala
modules/portal/app/controllers/portal/Bookmarks.scala
modules/portal/app/controllers/portal/Portal.scala
modules/portal/app/controllers/portal/account/Accounts.scala

TODO: fix underlying crapness causing us to map to a unit value

Back out change of Unit -> () since it breaks w/ Scala 2.12

---

modules/admin/app/actors/harvesting/OaiPmhHarvester.scala
modules/admin/app/actors/harvesting/OaiPmhHarvesterManager.scala
modules/admin/app/actors/harvesting/ResourceSyncHarvester.scala
modules/admin/app/actors/harvesting/ResourceSyncHarvesterManager.scala
modules/admin/app/actors/transformation/XmlConverter.scala
modules/admin/app/actors/transformation/XmlConverterManager.scala
modules/admin/app/assets/js/components/convert-manager.js
modules/admin/app/controllers/institutions/DataTransformations.scala
modules/admin/app/models/ConvertConfig.scala
modules/admin/app/services/transformation/utils/package.scala
modules/admin/conf/messages
test/actors/harvesting/OaiPmhHarvesterManagerSpec.scala
test/actors/transformation/XmlConverterSpec.scala

Various other tweaks to the resourcesync harvester, and addition of a test for XmlConverter behaviour

Don't do unnecessary work re-converting files already converted w/ same settings 

---

conf/evolutions/default/1.sql
modules/admin/app/actors/ingest/DataImporter.scala
modules/admin/app/actors/ingest/DataImporterManager.scala
modules/admin/app/assets/js/components/ingest-manager.js
modules/admin/app/assets/js/datamanager-dao.js
modules/admin/app/controllers/admin/Ingest.scala
modules/admin/app/controllers/institutions/ImportConfigs.scala
modules/admin/app/controllers/institutions/ImportFiles.scala
modules/admin/app/controllers/institutions/Repositories.scala
modules/admin/app/controllers/sets/AuthoritativeSets.scala
modules/admin/app/controllers/units/DocumentaryUnits.scala
modules/admin/app/controllers/vocabularies/Vocabularies.scala
modules/admin/app/models/ImportConfig.scala
modules/admin/app/models/IngestParams.scala
modules/admin/app/models/IngestResult.scala
modules/admin/app/services/ingest/ImportConfigService.scala
modules/admin/app/services/ingest/ImportLogService.scala
modules/admin/app/services/ingest/IngestService.scala
modules/admin/app/services/ingest/SqlImportConfigService.scala
modules/admin/app/services/ingest/SqlImportLogService.scala
modules/admin/app/services/ingest/WSIngestService.scala
modules/admin/app/views/admin/repository/datamanager.scala.html
modules/admin/app/views/admin/tools/ingest.scala.html
modules/admin/conf/institutions.routes
test/actors/ingest/DataImporterManagerSpec.scala
test/integration/admin/IngestSpec.scala
test/resources/import-config-fixtures.sql
test/services/ingest/MockIngestService.scala
test/services/ingest/SqlImportConfigServiceSpec.scala
test/services/ingest/SqlImportLogServiceSpec.scala

This will eventually be used for scheduled ingests

Make import configuration persistent,

---

modules/admin/app/assets/js/components/ingest-manager.js
modules/admin/app/assets/js/components/oaipmh-manager.js
modules/admin/app/assets/js/components/rs-manager.js
modules/admin/app/assets/js/datamanager-dao.js

It would be nice if the commonalities could be extracted somehow, since there are many of them, but that brings its own problems.

Bring more consistency to the RS/OAIPMH/Ingest UIs

---

etc/db_migrations/20210309_add_import_config_table.sql
modules/admin/app/assets/js/datamanager.worker.js

Also add a migration file for the import_config table

Fix missing parameter on transformation preview

---

modules/portal/conf/messages
modules/portal/conf/messages.de
modules/portal/conf/messages.fr
modules/portal/conf/messages.pl

Remove mention of (now hidden) feedback menu from contact page.

---

conf/logback-play-dev.xml
modules/admin/conf/admin.routes
modules/admin/conf/countries.routes
modules/admin/conf/cypher.routes
modules/admin/conf/groups.routes
modules/admin/conf/sets.routes
modules/admin/conf/tools.routes
modules/admin/conf/users.routes
modules/admin/conf/virtual.routes
modules/admin/conf/vocabularies.routes
modules/api/conf/api.routes
modules/guides/conf/guides.routes
modules/portal/conf/account.routes
modules/portal/conf/portal.routes
modules/portal/conf/profile.routes
project/build.properties
project/plugins.sbt

Also add parens to various route definitions, which is now mandatory and in any case necessary for Scala 2.13

Update to Play 2.8.8 and SBT 1.4.9

---

modules/portal/app/views/country/searchItem.scala.html

TODO: make a system for this or a help to get it from config

Add hacky hard-coded URL for country icon images.

---

modules/admin/app/controllers/institutions/Repositories.scala
modules/portal/app/controllers/portal/users/UserProfiles.scala
modules/portal/app/services/storage/FileStorage.scala
test/integration/portal/UserProfilesSpec.scala

Also fix the repository profile image uploader, which was broken.

Append a stamp to uploaded profile images to prevent caching issues

---

modules/admin/app/assets/css/datamanager.scss
modules/admin/app/assets/js/datamanager/components/_dataset-manager.vue
modules/admin/app/assets/js/datamanager/components/_mixin-stage.vue

Also put a max height on the dataset switcher list

Ensure harvest/ingest state is reset when switching datasets

---

build.sbt
conf/evolutions/default/1.sql
etc/db_migrations/20210706_add_use_source_id_to_import_params.sql
modules/admin/app/actors/transformation/XmlConverter.scala
modules/admin/app/assets/js/datamanager/components/_modal-ingest-config.vue
modules/admin/app/assets/js/datamanager/types.ts
modules/admin/app/controllers/datasets/ImportConfigs.scala
modules/admin/app/models/ImportConfig.scala
modules/admin/app/models/IngestParams.scala
modules/admin/app/services/ingest/SqlImportConfigService.scala
modules/admin/app/services/ingest/WSIngestService.scala
modules/admin/app/views/admin/ingest/ingest.scala.html
test/resources/import-config-fixtures.sql

Also attempt to make some conversion operations more robust to transitory S3 errors.

Add a use_source_id field to the import config and options

---

modules/admin/app/assets/js/datamanager/components/_manager-convert.vue
modules/admin/app/assets/js/datamanager/components/_transformation-editor.vue
modules/admin/conf/transform.xqy
modules/admin/conf/xtra.xqm

Also mark XQuery scripts as UTF-8

Respect input content type encoding in transformation editor

---

modules/admin/app/assets/js/datamanager/common.ts
modules/admin/app/assets/js/datamanager/components/_manager-datasets.vue
modules/admin/app/assets/js/datamanager/components/_manager-oaipmh.vue
modules/admin/app/assets/js/datamanager/components/_manager-rs.vue
modules/admin/app/assets/js/datamanager/components/_manager-upload.vue
modules/admin/app/assets/js/datamanager/components/_mixin-stage.vue
modules/admin/app/assets/js/datamanager/components/_mixin-util.vue
modules/admin/app/assets/js/datamanager/types.ts
modules/admin/app/controllers/datasets/ImportDatasets.scala
modules/admin/app/controllers/datasets/ImportFiles.scala

- relative time displays 'Just now' for under 1 minute (this prevents rapid incrementing of seconds when the list refreshes)
- dataset file counts update when harvesting or deleting files
- dataset is closed when deleted

Fix various issues with the dataset manager and file lists

---

.gitignore
README.md
conf/minio.conf.example
docker-compose-dev.yml
docker-compose-minio.yml
docker-compose.yml

Add a docker-compose file for specifically development.

---

modules/portal/app/services/htmlpages/GoogleDocsHtmlPages.scala

Remove #banner element from Google Docs content

---

conf/evolutions/default/1.sql
etc/db_migrations/20210923_add_import_dataset_status_column.sql
modules/admin/app/assets/css/datasets.scss
modules/admin/app/assets/js/datasets/components/_manager-dataset-list.vue
modules/admin/app/assets/js/datasets/components/_modal-dataset-config.vue
modules/admin/app/assets/js/datasets/types.ts
modules/admin/app/models/ImportDataset.scala
modules/admin/app/services/datasets/SqlImportDatasetService.scala
test/integration/admin/ImportDatasetsSpec.scala
test/resources/data-transformation-fixtures.sql
test/resources/import-dataset-fixtures.sql

Also make them editable from the main list

Add a 'status' column for import datasets

---

app/ErrorHandler.scala
build.sbt
docker-compose.yml
modules/api/app/controllers/api/v1/ApiV1.scala
modules/backend/src/main/scala/services/data/DataServiceError.scala
modules/backend/src/main/scala/services/data/WebServiceHelpers.scala
modules/backend/src/main/scala/services/data/WsDataService.scala
modules/core/src/main/scala/controllers/base/CoreActionBuilders.scala
modules/core/src/main/scala/controllers/generic/Read.scala
modules/portal/app/controllers/portal/base/PortalController.scala
modules/portal/app/views/common/optionsOnError.scala.html
modules/portal/app/views/errors/gone.scala.html
modules/portal/app/views/errors/itemNotFound.scala.html
modules/portal/app/views/errors/pageNotFound.scala.html
modules/portal/conf/messages
test/integration/admin/ApiSpec.scala
test/integration/admin/DocumentaryUnitViewsSpec.scala
test/integration/admin/SupervisorWorkerIntegrationSpec.scala
test/integration/portal/SignupSpec.scala
test/services/data/WsDataServiceSpec.scala

This returns a different response for deleted items than a regular 404.

Implement HTTP 410 tombstone responses

---

modules/admin/app/controllers/groups/Groups.scala
modules/admin/app/views/admin/group/show.scala.html
modules/admin/app/views/admin/userProfile/show.scala.html

Also make user emails available to admin users

Show more user info in various admin contexts, such as group lists

---

modules/admin/app/controllers/cypher/CypherQueries.scala
modules/admin/app/views/admin/cypherQueries/adminActions.scala.html
modules/admin/app/views/admin/cypherQueries/check.scala.html
modules/admin/app/views/admin/cypherQueries/delete.scala.html
modules/admin/app/views/admin/cypherQueries/list.scala.html
modules/admin/conf/cypher.routes
modules/admin/conf/messages
modules/backend/src/main/scala/services/cypher/CypherService.scala
modules/backend/src/main/scala/services/cypher/WsCypherService.scala

This is a bit rough but it should suffice for admin purposes

Add bulk validation of Cypher queries for when upgrading Neo4j

---

.circleci/config.yml

Update the image on the CircleCI configuration

---

modules/admin/app/assets/js/datasets/api.ts
modules/admin/app/assets/js/datasets/components/_manager-coreference.vue
modules/admin/app/assets/js/datasets/components/_manager-dataset-list.vue
modules/admin/app/assets/js/datasets/components/_manager-timeline.vue
modules/admin/app/controllers/datasets/CoreferenceTables.scala
modules/admin/app/controllers/datasets/ImportDatasets.scala
modules/admin/app/services/ingest/CoreferenceService.scala
modules/admin/app/services/ingest/SqlCoreferenceService.scala
modules/admin/conf/datasets.routes
test/integration/admin/CoreferenceTablesSpec.scala
test/services/ingest/SqlCoreferenceServiceSpec.scala

- separated methods for import (from external) and building from DB
- added way to delete references
- misc cleanups and polishing

Enhancements to the management of coreferences

---

modules/admin/app/assets/js/datasets/api.ts
modules/admin/app/assets/js/datasets/components/_manager-dataset-list.vue
modules/admin/app/controllers/datasets/ImportDatasets.scala
modules/admin/conf/datasets.routes

Counts are now loaded lazily in an async manner

Fix slow loading of dataset list due to waiting for file counts

---

build.sbt
modules/admin/conf/datasets.routes

Also rename one route in the dataset manager

Add digest to the admin asset pipeline, for use in versioning

---

modules/admin/app/assets/css/admin/_admin.scss
modules/admin/app/views/admin/common/testWarning.scala.html
modules/admin/app/views/admin/userProfile/statusBadges.scala.html
modules/guides/app/assets/css/guides.scss
modules/portal/app/assets/css/portal.scss
modules/portal/app/assets/css/portal/_layout.scss
modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/assets/css/portal/_variables.scss
modules/portal/app/views/common/flash.scala.html

- give the right sidebar an auto margin to prevent re-layout on load
- don't output Bootstrap grid classes
Also mark staff as staff in the admin user list

Attempts to optimise some SCSS

---

conf/search.conf
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala

This is so we can add multilingual fields as needed...

Move the list of search fields to config and make extensible

---

docker-compose-minio.yml
docker-compose.yml

This resolves the previous issue with version listing

Update minio version

---

modules/portal/public/robots.txt
modules/portal/public/sitemap.xml

Block GPTbot and add more URLs to the sitemap.xml

Update sitemap and robots.txt

---

conf/application.conf
modules/portal/conf/messages.es

Hi there,
I have been working on this Spanish translation of the EHRI portal public site. I have based the translation on the official translations from the ICA for all the archival terminology, so I hope this part is correct. For the rest of the texts I have done my own translations, trying to be consistent and using the most generic Spanish possible that could match all the variants in Spain and Latin America.
I hope this is useful for EHRI in order to reach more institutions in Spanish-speaking countries!
Best,
Herminio

Added Spanish translation for the public site

---

.editorconfig
.gitignore
conf/search.conf
modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala

Added `op` and `df` to default query params

Improve compatibility w/ Solr 7

---

conf/evolutions/default/1.sql
etc/db_migrations/20240129_add_import_url_set_config_method_column.sql
modules/admin/app/actors/harvesting/UrlSetHarvester.scala
modules/admin/app/assets/js/datasets/components/_form-http-headers.vue
modules/admin/app/assets/js/datasets/components/_form-http-method.vue
modules/admin/app/assets/js/datasets/components/_modal-urlset-config.vue
modules/admin/app/controllers/datasets/HarvestConfigs.scala
modules/admin/app/models/UrlSetConfig.scala
modules/admin/app/services/harvesting/SqlUrlSetConfigService.scala
test/actors/cleanup/CleanupRunnerManagerSpec.scala
test/actors/harvesting/HarvesterManagerSpec.scala
test/actors/harvesting/UrlSetHarvesterSpec.scala
test/integration/admin/HarvestConfigsSpec.scala
test/resources/import-url-set-config-fixtures.sql

Support POST requests for URL set harvesting

---

.github/workflows/ci.yml
build.sbt
conf/search.conf

This also enables alternative language country names
Fixes #1490

Update indexer and add urls search field to defaults

---

build.sbt
conf/application.conf
conf/logback-play-dev.xml
conf/test.conf
modules/core/src/main/scala/models/Address.scala
modules/portal/app/guice/AppModule.scala
modules/portal/app/services/geocoding/AwsGeocodingService.scala
modules/portal/app/services/geocoding/GeocodingService.scala
test/helpers/TestConfiguration.scala
test/services/geocoding/NoopGeocodingService.scala

The old Bing one seems sadly defunct

Implement the repository geocoder using AWS Location service

---

modules/portal/app/auth/oauth2/providers/MicrosoftOAuth2Provider.scala
modules/portal/app/views/Helpers.scala

It requires authorization to fetch, logic which we don't have yet.
Fixes #1447

Ignore the picture from Microsoft OAuth data

---

modules/portal/app/assets/css/portal/_layout.scss
modules/portal/app/assets/css/portal/_style.scss
modules/portal/app/views/account/changePasswordForm.scala.html
modules/portal/app/views/account/forgotPassword.scala.html
modules/portal/app/views/account/login.scala.html
modules/portal/app/views/account/loginForm.scala.html
modules/portal/app/views/account/oauth2Form.scala.html
modules/portal/app/views/account/register.scala.html
modules/portal/app/views/account/resetPassword.scala.html
modules/portal/app/views/account/signupForm.scala.html
modules/portal/public/img/facebook-signin-icon.svg
modules/portal/public/img/google-signin-icon.svg
modules/portal/public/img/microsoft-signin-icon.svg
modules/portal/public/img/openid-signin-icon.svg
modules/portal/public/img/yahoo-signin-icon.svg
project/plugins.sbt

Use more recent branding for MS/Google/FB/Yahoo

Finally rework the extremely outdated login/signup page

---

modules/admin/app/assets/css/admin/_admin.scss
modules/admin/app/views/admin/concept/descriptionForm.scala.html
modules/admin/app/views/admin/repository/addressForm.scala.html
modules/portal/app/assets/css/portal/_layout.scss

These got jumbled due to some unexpected CSS interactions which prevented the add element button from working.
Fixes #1510

Improve display of inline form elements on narrow screen widths

---

modules/portal/app/views/account/changePasswordForm.scala.html

This caused it to go to 100% width and look ugly

Remove a class from the password form button

---

conf/application.conf
modules/admin/app/assets/js/datasets/components/_mixin-preview-panel.vue
modules/admin/app/views/admin/datasets/manager.scala.html

Also set preview size by external config

Hackily remove potential UTF-8 BOMs from XML data in the preview
