- project/Build.scala
This shuts up most instances of the multiple instances on classpath problem that results from both Play and Neo4j packaging a logback.xml, albeit not all of them. SBT seems to prompt some logback output of its own somewhere outside of our projects and I'm not entirely sure where this is coming from. Still, it's an improvement.
> Set logback conf file path explicitly in build for testing.

- test/integration/portal/AnnotationsSpec.scala
- test/utils/search/MockSearchDispatcher.scala
When testing a page which used a user's annotations via the search engine, no results would have been returned since the mock ignored these. However, since we were testing the wrong data this went unnoticed.
> Add annotations to mock search results and fix erroneous test.

- conf/application.conf
- modules/admin/app/views/admin/link/accessPointLinks.scala.html
- modules/backend/app/backend/Descriptions.scala
- modules/backend/app/backend/rest/RestDescriptions.scala
- test/integration/DocumentaryUnitViewsSpec.scala
Lots of access-point related fixes. When access points were deleted two things went wrong:
- the item's cache wasn't cleared
- it was erroneously delete from the search engine (!)
- refactor backend description-deleted methods to match newer style, using context bounds instead of implicit parameters for the resource/writeable types
Better late than never...
> Fix bugs 592 and 593.

- project/Build.scala
This file has previously been (erroneously) deployed, and the app was reading it instead of the prod file, which also was not being included in the prod conf. This meant that when the site was deployed from the test instance the external pages stopped working.
> Ensure any test external pages conf is not deployed. This led to #597.

- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/core/app/controllers/base/CoreActionBuilders.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/app/controllers/portal/base/PortalController.scala
These were using `OptionalAuthAction` directly, which was bad.
Fixes #560.
> Prevent certain actions evading the maintenance etc filters.

- modules/core/app/controllers/generic/Linking.scala
- test/integration/DocumentaryUnitViewsSpec.scala
Due to the confusingness of the search API, this was not being applied
as previously.
TODO: Fix the search API to be less confusing.
Fixes #606.
> Fix entity type restrictions on the link item select view.

- modules/guides/app/controllers/portal/guides/Guides.scala
The previous default of 1.0 (km) didn't work for the Jewish council guide, and just happened to work for the Terezin one because most the of geo facets are closely clustered around the same point.
Fixes #615.
> Change the default distance for geo facets, when none specified in the query.

- modules/portal/conf/portal.routes
- test/integration/portal/PortalSpec.scala
IDs can now only be word-chars.
> Restrict the format of external page ids (fixes #635)

- modules/backend/src/main/scala/backend/rest/RestDAO.scala
- project/Build.scala
- test/backend/BackendModelSpec.scala
Some additional cleanup. Bumb backend version.
Fixes #640.
> URL encode log message values to prevent higher chars getting mangled.

- conf/logback-play-dev.xml
- modules/admin/app/controllers/admin/ApiController.scala
- modules/backend/src/main/scala/backend/rest/RestDAO.scala
- modules/backend/src/main/scala/backend/rest/RestEvents.scala
- modules/backend/src/main/scala/backend/rest/RestGeneric.scala
- modules/core/app/controllers/core/auth/oauth2/OAuth2LoginHandler.scala
- modules/portal/app/indexing/SearchToolsIndexMediator.scala
- project/Build.scala
- project/plugins.sbt
- test/backend/BackendModelSpec.scala
Update client for backend 0.11.0.
- remove `/list` from list endpoints
- do counting via `HEAD` requests on the list endpoints
- fixes for finer-grained logging on backend
- update to Play 2.4.3
- tweak index mediator API
- small tweaks to the build
> Updates for backend 0.11.0 etc

- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/utils/ead/ToEadSerializer.java
- modules/admin/test/views/export/ead/ToEadSerializerSpec.scala
Also ensure external web links are XML encoded.
Fixes #655.
> Use chunked encoding for EAD export, since we don't know the size.

- .travis.yml
- conf/logback-play-dev.xml
- modules/admin/app/controllers/admin/ApiController.scala
- modules/admin/app/controllers/admin/Utils.scala
- modules/backend/src/main/scala/backend/rest/RestHelpers.scala
- project/Build.scala
- Bumped backend to 0.11.1, Neo4j to 2.3.0, and Scala to 2.11.7.
- Some additional cleanups to build and logger config.
- Don't chunk Cypher responses when query came via Ajax.
JS doesn't handle chunked responses very nicely. Also tweak some
Cypher queries to use MATCH and labels instead of START.
> Update toNeo4j 2.3

- modules/admin/app/controllers/authorities/HistoricalAgents.scala
- modules/admin/app/controllers/institutions/Repositories.scala
- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/historicalAgent/adminActions.scala.html
- modules/admin/app/views/admin/repository/adminActions.scala.html
- modules/admin/conf/authorities.routes
- modules/admin/conf/institutions.routes
- modules/admin/conf/messages
- modules/backend/src/main/scala/backend/rest/RestDAO.scala
- modules/core/app/controllers/generic/Generic.scala
- project/plugins.sbt
- test/integration/DocumentaryUnitViewsSpec.scala
- test/integration/EntityViewsSpec.scala
- test/integration/RepositoryViewsSpec.scala
- Roll back to Play 2.4.3 for the moment since 2.4.4 has some issues
- Revise method for forwarding backend requests directly.
- Remove some default accepts/content-type headers from backend
call helpers (relying on the default)
- Added menu items and controller actions.
> Add EAC and EAG export and tweak implementation

- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/historicalAgent/description.scala.html
- modules/admin/app/views/admin/historicalAgent/descriptionForm.scala.html
- modules/admin/app/views/formHelpers/inlineName.scala.html
- modules/admin/app/views/formHelpers/inlineNameSet.scala.html
- modules/admin/app/views/formHelpers/inlineText.scala.html
- modules/admin/app/views/formHelpers/inlineTextSet.scala.html
- modules/core/app/models/HistoricalAgentDescription.scala
- modules/core/test/resources/historicalAgent.json
- modules/portal/app/assets/js/admin.js
- modules/portal/app/views/historicalAgent/description.scala.html
- Additionally, fix display of popover field description text on multi-value name and text fields.
> Convert some authority description fields to multi-value.

- modules/admin/app/controllers/authorities/HistoricalAgents.scala
- modules/admin/app/controllers/institutions/Repositories.scala
- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/documentaryUnit/adminActions.scala.html
- modules/admin/app/views/admin/historicalAgent/adminActions.scala.html
- modules/admin/app/views/admin/repository/adminActions.scala.html
- modules/admin/conf/authorities.routes
- modules/admin/conf/institutions.routes
- modules/admin/conf/units.routes
- modules/portal/app/controllers/portal/DocumentaryUnits.scala
- modules/portal/app/controllers/portal/HistoricalAgents.scala
- modules/portal/app/controllers/portal/Repositories.scala
- modules/portal/conf/portal.routes
- test/integration/admin/DocumentaryUnitViewsSpec.scala
- test/integration/admin/EntityViewsSpec.scala
- test/integration/admin/RepositoryViewsSpec.scala
- test/integration/portal/PortalSpec.scala
Not yet exposed/linked to on the interface (yet.)
Currently, whilst the URLs are uniform (/export), the formats for each type respectively are hard-coded.
> Move EAC/EAD/EAG export functionality from admin to portal.

- modules/admin/app/controllers/cypher/CypherQueries.scala
- modules/admin/app/views/admin/cypherQueries/list.scala.html
- modules/admin/conf/cypher.routes
- modules/backend/src/main/scala/backend/rest/RestAnnotations.scala
- modules/backend/src/main/scala/backend/rest/RestContext.scala
- modules/backend/src/main/scala/backend/rest/RestEvents.scala
- modules/backend/src/main/scala/backend/rest/RestPermissions.scala
- modules/backend/src/main/scala/defines/ContentTypes.scala
- modules/backend/src/main/scala/defines/EntityType.scala
- modules/portal/app/controllers/DataFormat.scala
- modules/portal/app/controllers/portal/users/UserProfiles.scala
- modules/portal/app/models/CypherQuery.scala
- modules/portal/app/utils/CsvHelpers.scala
- modules/portal/app/views/userProfile/annotationList.scala.html
- modules/portal/app/views/userProfile/itemWatchList.scala.html
- modules/portal/conf/messages
- modules/portal/conf/messages.de
- modules/portal/conf/messages.fr
- modules/portal/conf/messages.pl
Also, remove some hard-coded entity name strings which will break when we rename them.
> Add tab-separated value support to note, watch lists, and Cypher data.

- modules/admin/app/controllers/admin/LegacyAccounts.scala
- modules/admin/app/controllers/admin/Utils.scala
- modules/portal/app/models/CypherQuery.scala
- modules/portal/app/utils/CsvHelpers.scala
- modules/portal/test/utils/CsvHelpersSpec.scala
- project/Build.scala
Jackson does on-demand quoting, rather than quoting being either on or off for all values. It also has a slightly nicer API.
Fixes #697.
> Migrate from OpenCSV to Jackson CSV

- modules/core/app/models/DocumentaryUnitDescription.scala
- modules/portal/app/controllers/portal/users/UserProfiles.scala
- modules/portal/app/models/ProfileData.scala
- test/integration/portal/UserProfilesSpec.scala
The current PATCH semantics are a bit broken since null values get removed before the data merged, which prevents removing values. This provides a workaround for the immediate case of updating user profiles by merging the patch data on the client side and using update instead of patch.
> Fix updating profile info when removing data.

- modules/admin/app/controllers/admin/Data.scala
This time it was broken because a backported change from the Play 2.5 branch pointed to the wrong backend WS path.
> Fix JSON export (again).

- conf/application.conf
- modules/admin/app/assets/js/access-points.js
- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/documentaryUnit/editAccessPoints.scala.html
- modules/core/app/controllers/generic/Search.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
This is accomplished via a config value which takes their IDs.
A few small extra tweaks.
Fixes #722.
> Allow constraining access point suggestions to specific vocabs/sets.

- conf/search.conf
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
Since there's no comment to tell us why this was added, it's being removed due to having weird effects on the quick filter (returning items in Ukrainian despite an English search string).
Also add a search field alias for the language code.
> Remove group.sort Solr parameter.

- modules/admin/app/controllers/admin/AdminSearch.scala
- modules/admin/app/views/admin/authoritativeSet/show.scala.html
- modules/admin/app/views/admin/concept/adminActions.scala.html
- modules/admin/app/views/admin/country/adminActions.scala.html
- modules/admin/app/views/admin/group/show.scala.html
- modules/admin/app/views/admin/historicalAgent/adminActions.scala.html
- modules/admin/app/views/admin/repository/adminActions.scala.html
- modules/admin/app/views/admin/vocabulary/show.scala.html
- remove superfluous sidebar actions (history link already exists in the recent-action panel)
- fix entity type restriction in global search facet
> More admin cleanups.

- modules/admin/app/controllers/admin/AdminSearch.scala
- modules/core/app/controllers/generic/Indexable.scala
- modules/core/app/utils/search/SearchIndexMediator.scala
- modules/portal/app/indexing/CmdlineIndexMediator.scala
- modules/portal/app/indexing/SearchToolsIndexMediator.scala
This fixes the deprecation messages resulting from using the old API.
> Use an actor instead of a concurrent channel as the index message sink

- modules/backend/src/main/scala/backend/rest/RestService.scala
- test/integration/admin/DocumentaryUnitViewsSpec.scala
Using escaped '?' and '#' in the external URL results in malformed URLs being sent to the backend. A nicer way to fix this would be to use a proper URIBuilder, such as that which comes with JAX RS, but
that's a big dependency.
> Fix unescaped URL path segments being passed to the backend.

- modules/admin/app/views/admin/concept/descriptionForm.scala.html
- modules/core/app/models/ConceptDescription.scala
- modules/portal/conf/messages
This exists on the EHRI thesaurus, so it should be editable.
> Add CVOC Concept identifier (ergo, script code) as an optional field

- app/AppModule.scala
- conf/evolutions/postgres/1.sql
- modules/admin/app/controllers/admin/Utils.scala
- modules/admin/app/views/admin/movedItemsForm.scala.html
- modules/portal/app/utils/SqlMovedPageLookup.scala
- test/helpers/FakeMultipartUpload.scala
- test/integration/admin/UtilsSpec.scala
Page URL is now properly encoded in DB, as it is received in the request. When uploading moved items, encoding is now done before insert. Added a test.
Additional changes:
- fixed an issue with the Postgres evolution
- renamed the SQL moved page implementation
- allow file upload tester to have additional form data
Fixes #804.
> Fix issues with redirecting moved pages.

- modules/core/app/auth/sql/SqlAccountManager.scala
- test/auth/MockAccountManager.scala
- test/auth/SqlAccountManagerSpec.scala
- test/integration/portal/AccountsSpec.scala
Previously this relied on MySQL behaviour to work as expected.
Fixes #816.
> Lookup emails case-insensitively.

- app/ErrorHandler.scala
- modules/backend/src/main/scala/backend/ServiceException.scala
- modules/backend/src/main/scala/backend/rest/BackendOffline.scala
- modules/backend/src/main/scala/backend/rest/RestService.scala
- modules/core/app/utils/search/SearchEngineOffline.scala
- modules/core/app/utils/search/package.scala
- modules/portal/app/controllers/portal/PortalData.scala
- modules/portal/app/views/errors/searchEngineError.scala.html
- modules/portal/conf/messages
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
- test/helpers/TestConfiguration.scala
- test/integration/portal/PortalSpec.scala
This allows us to provide better error messages, no longer conflating the cause when the DB or the search engine is down.
Some additional tweaks to test code to make some vals protected.
> Catch and rethrow backend/search errors with wrapped exceptions.

- app/AppModule.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrJsonResponseHandler.scala
- modules/solr/src/test/resources/solrQueryResponse1.json
- modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryParserSpec.scala
Also: rename the Solr JSON response parser.
Fixes #821.
> Fix spellcheck by adapting the Solr response parser for Solr 6.

- modules/admin/app/controllers/admin/Utils.scala
- modules/admin/conf/admin.routes
- modules/backend/src/main/scala/backend/DataApi.scala
- modules/backend/src/main/scala/backend/rest/RestApi.scala
- modules/core/app/utils/search/SearchEngine.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
- test/integration/admin/UtilsSpec.scala
- test/utils/search/MockSearchEngineConfig.scala
Add status() methods to data and search services and monitor both in the monitoring URI. This should alert us when Solr is down.
> Better monitoring of search.

- modules/core/app/models/ConceptDescription.scala
- modules/core/app/models/DocumentaryUnitDescription.scala
- modules/core/app/models/HistoricalAgentDescription.scala
- modules/core/app/models/RepositoryDescription.scala
- modules/core/app/models/base/Persistable.scala
- test/integration/admin/EntityViewsSpec.scala
This fixes an error when those types have validation issues.
> Add relationship metadata on access points, unknown rels, and maint events

- modules/portal/app/controllers/portal/FacetConfig.scala
- modules/portal/app/controllers/portal/Portal.scala
- modules/portal/app/utils/Stats.scala
This difference was due to including superfluous entity types.
> Fix discrepency between no. item-holding institutions on front and list pages

- modules/admin/app/controllers/virtual/VirtualUnits.scala
- modules/api/app/controllers/api/v1/ApiV1.scala
- modules/api/app/models/api/v1/JsonApiV1.scala
- modules/api/conf/api.routes
- modules/core/app/controllers/generic/Search.scala
- modules/core/app/models/VirtualUnit.scala
- modules/core/app/utils/search/SearchParams.scala
- modules/core/app/utils/search/package.scala
- modules/core/test/utils/search/FacetSpec.scala
- modules/portal/app/controllers/base/SearchVC.scala
- modules/portal/app/controllers/portal/VirtualUnits.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
Changes to expand the scope of the API:
- generic facets are now supported for search via `facet=class:value`
- added a language-of-description facet to the API
- added support for fetching/searching virtual collections in the API
Misc. changes to other VC code.
> Support for generic facets and virtual units in the API

- app/Filters.scala
- conf/application.conf
- test/integration/api/v1/ApiV1Spec.scala
Allows cross-origin API calls without JSONP.
> Add the global CORS filter and /api set as a path prefix.

- modules/admin/app/controllers/admin/Utils.scala
- modules/admin/app/models/admin/FindReplaceTask.scala
- modules/admin/app/views/admin/Helpers.scala
- modules/admin/app/views/admin/findReplace.scala.html
- modules/admin/app/views/admin/layout/adminNavBar.scala.html
- modules/admin/conf/admin.routes
- modules/admin/conf/messages
- modules/backend/src/main/scala/defines/ContentTypes.scala
- modules/backend/src/main/scala/defines/EntityType.scala
- modules/core/app/controllers/generic/Indexable.scala
- modules/core/app/global/GlobalEventHandler.scala
- modules/core/app/utils/search/SearchIndexMediator.scala
- modules/portal/app/indexing/CmdlineIndexMediator.scala
- modules/portal/app/indexing/SearchToolsIndexMediator.scala
- test/backend/RestApiSpec.scala
- test/helpers/TestConfiguration.scala
- test/integration/admin/UtilsSpec.scala
- test/utils/search/MockSearchIndexMediator.scala
This is admin only since it's a pretty sharp tool which requires knowing a bit about the database schema (specifically, the key names for item attributes.)
Also refactor the admin menu a bit to accommodate new features.
Also in this patch: small tweak to the index mediator API to better accommodate reindexing multiple items by ID.
> Add a UI to backend find/replace web service function.

- modules/core/app/utils/search/FacetClass.scala
- modules/core/app/utils/search/SearchResult.scala
- modules/portal/app/controllers/portal/Portal.scala
- modules/portal/app/utils/Stats.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/QueryResponseExtractor.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrJsonResponseHandler.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
- modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryParserSpec.scala
This is much faster (1 second vs. 8 in production) and more efficient, though the method of extracting the data is quite fiddly. It also requires the leaky abstraction of the search engine to be made more leaky.
> Replace method of extracting item stats from facets w/ JSON facets for Solr 6

- build.sbt
- conf/application.conf
- modules/admin/app/controllers/admin/Utils.scala
- modules/admin/app/views/admin/Helpers.scala
- modules/admin/app/views/admin/renameItemsForm.scala.html
- modules/admin/conf/admin.routes
- modules/admin/conf/messages
- modules/backend/src/main/scala/backend/DataApi.scala
- modules/backend/src/main/scala/backend/rest/RestApi.scala
- modules/backend/src/main/scala/backend/rest/RestService.scala
- modules/portal/app/indexing/SearchToolsIndexMediator.scala
- test/integration/admin/UtilsSpec.scala
- Allows upload of 2-col CSV of ID -> new local identifier, and handles updating the search index and creating 301s.
- Add data API wrappers for various backend utility methods.
- Bump the backend API version as well.
> Add more support for handling item renaming from the admin UI.

- project/plugins.sbt
- test/helpers/TestConfiguration.scala
- test/integration/admin/BrowserSpec.scala
- test/integration/admin/UtilsSpec.scala
- test/integration/portal/PortalSpec.scala
- test/mockdata/package.scala
- test/utils/MockMovedPageLookup.scala
Because the mock redirect DB is mutable, tests can interfere with each other if run in a certain order. To workaround this for the time being we just clear the buffer after adding to it.
> Update Play and fix a fragile test.

- build.sbt
- modules/admin/app/controllers/admin/Data.scala
- modules/backend/src/main/scala/backend/DataApi.scala
- modules/backend/src/main/scala/backend/rest/RestApi.scala
- modules/core/app/backend/rest/resolvers.scala
- modules/core/app/controllers/generic/Search.scala
- modules/core/app/utils/search/SearchHit.scala
- modules/core/app/utils/search/SearchItemResolver.scala
- modules/core/test/utils/search/SearchHitSpec.scala
- modules/guides/app/controllers/portal/guides/Guides.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrJsonResponseParser.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrSearchEngine.scala
- modules/solr/src/test/scala/eu/ehri/project/search/solr/SolrQueryParserSpec.scala
- test/backend/RestApiSpec.scala
- test/utils/search/MockSearchEngine.scala
This means we always get back a list the same length as that put in.
Also make Solr hit fields JsValues instead of flattening them to strings.
> Change semantics of backup /fetch endpoint so invalid items are null.

- modules/core/app/controllers/base/ControllerHelpers.scala
- modules/core/app/controllers/base/CoreActionBuilders.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
To be set combined with the `play.http.forwarded` conf values.
> Remove an old hack for getting forwarded remote address.

- modules/api/app/views/api/graphql/docs.scala.html
- modules/api/app/views/api/graphql/graphiql.scala.html
This is backwards incompatible w/ the server due to the way parameters
are handled (no longer stringified).
> Update GraphiQL to the much better 0.11.10 version.

- app/AppModule.scala
- build.sbt
- modules/portal/app/utils/markdown/CommonmarkMarkdownRenderer.scala
- modules/portal/app/utils/markdown/FlexmarkMarkdownRenderer.scala
- modules/portal/app/utils/markdown/RawMarkdownRenderer.scala
- modules/portal/app/utils/markdown/SanitisingMarkdownRenderer.scala
- modules/portal/test/utils/markdown/CommonmarkMarkdownRendererSpec.scala
- modules/portal/test/utils/markdown/FlexmarkMarkdownRendererSpec.scala
- modules/portal/test/utils/markdown/SanitisingMarkdownRendererSpec.scala
- Split renderer between a 'raw' renderer, and one which does
sanitisation, which makes it easier to substitute different
implementations
- Add a commonmark-java raw renderer implementation, now the
default
Flexmark is still in place.
> Refactor markdown renderers

- modules/portal/app/assets/css/admin/_admin.less
Prevent a visible box showing at the bottom of the screen when select2 is clicked
> Select2 fix

- modules/portal/app/views/common/listSorting.scala.html
- modules/portal/app/views/common/search/facetList.scala.html
- modules/portal/app/views/common/search/searchSort.scala.html
This is basically so search engines don't index hundreds of permutations of them pointlessly.
> Add rel='nofollow' to search ordering and facet links

- conf/application.conf
- modules/backend/src/main/scala/services/data/Constants.scala
- modules/backend/src/main/scala/services/data/DataApiService.scala
- modules/core/app/auth/handler/cookie/CookieAuthHandler.scala
Also use a Duration for session timeout, instead of integer seconds
> Move backend data cache expiration to config

- modules/backend/src/main/scala/services/data/BatchResult.scala
- modules/backend/src/main/scala/services/data/DataApi.scala
- modules/backend/src/main/scala/services/data/DataApiService.scala
- test/services/data/DataApiServiceSpec.scala
This is to help handle bulk update tasks such as geocoding.
> Add more streaming/batch methods to the API

- modules/core/app/models/Annotation.scala
- modules/core/app/models/base/Model.scala
- modules/portal/conf/messages
Previous changes exposed the raw model `toString`, which we don't ever want to use.
> Fix the way some items do language-specific stringification.

- modules/admin/app/views/admin/documentaryUnit/listItem.scala.html
- modules/admin/app/views/admin/search/searchItemListWithAdditionalContent.scala.html
- modules/admin/app/views/admin/virtualUnit/listItem.scala.html
- modules/admin/app/views/admin/virtualUnit/searchItemList.scala.html
- modules/portal/app/views/common/search/searchItemList.scala.html
- modules/portal/app/views/documentaryUnit/searchItem.scala.html
- modules/portal/app/views/virtualUnit/childItemSearch.scala.html
If there is no active search, the description closest to the current language is shown. If there is a search, we use the hit ID as a hint. Child item lists then anchor-link to the same language description.
> Change (again) the way child item descriptions are rendered wrt lang

- modules/admin/app/controllers/admin/Ingest.scala
- modules/admin/app/controllers/institutions/Repositories.scala
- modules/admin/app/controllers/sets/AuthoritativeSets.scala
- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/controllers/vocabularies/Vocabularies.scala
- modules/admin/app/services/ingest/IngestApiService.scala
- modules/admin/app/services/ingest/IngestParams.scala
- modules/admin/app/views/admin/vocabulary/adminActions.scala.html
- modules/admin/conf/admin.routes
- test/integration/admin/IngestSpec.scala
Ideally users with parent permissions in e.g. a vocabulary would be able to ingest SKOS, but this is difficult without making ingest task controller-specific.
> Since non-admin ingest doesn't work (:sadface:) lock down views

- app/ErrorHandler.scala
- modules/portal/app/controllers/portal/PortalData.scala
- modules/portal/conf/portal.routes
- test/integration/admin/ApplicationSpec.scala
Rather than redirecting all trailing slash requests, only do so if they trigger a 404. Ideally we'd check if the non-slash route matches anything, but not sure how to do this yet. This should be more
compatible with Play 2.7.x.
> Revise trailing-slash routing behaviour

- modules/portal/app/views/formHelpers/csrfToken.scala.html
Instead of erroring when we can't generate a token, instead skip insertion of the form, which should lead to a validation error if the form is used.
> Make CSRF erroring less aggressive

- modules/admin/app/views/admin/documentaryUnit/deleteDescription.scala.html
- modules/admin/app/views/admin/documentaryUnit/descriptionActions.scala.html
- modules/admin/conf/messages
This prevents the situation where an item is unfindable because all it's indexed descriptions have been removed.
Fixes #1010
> Prevent deleting the last description from an item.

- modules/admin/app/views/admin/common/descriptionForm.scala.html
- modules/admin/app/views/admin/documentaryUnit/descriptionForm.scala.html
- test/helpers/TestConfiguration.scala
- test/integration/admin/DocumentaryUnitViewsSpec.scala
- test/integration/admin/RepositoryViewsSpec.scala
Try and prevent a recurance of #1085 by testing that submitting the actual form (with no changes) results in the same model.
> Better testing of actual forms.

- README.md
- modules/portal/app/views/about.scala.html
- modules/portal/app/views/country/introNotice.scala.html
- modules/portal/app/views/terms.scala.html
- modules/portal/conf/messages
- modules/portal/conf/messages.de
- modules/portal/conf/messages.fr
- modules/portal/conf/messages.pl
... except in fixtures.
Linking to HTTPS websites can help secure connections to the EHRI infrastructure.
> Use HTTPS for EHRI and Docker websites

- conf/search.conf
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
This should (hopefully) fix #746 without breaking any other behaviour, since the setting is local to the text query.
> Allow setting Solr op mode to AND as local param in q text

- modules/core/app/controllers/generic/Search.scala
- modules/core/app/services/search/SearchQuery.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
This is a way of favouring the description that is most appropriate to the user's current language, without affecting actual query results.
> Sort search groups with those matching the current language top.

- build.sbt
- project/build.properties
1.2.7 seems to be incredibly slow to run a refresh, takes longer to load, and seems to leak memory like crazy.
> Downgrade SBT back to 0.13.17

- build.sbt
- modules/portal/app/assets/css/ehri/_layouts.scss
- modules/portal/app/views/common/head.scala.html
This once existed to bundle IE9 fixes, but it's no longer supported.
> Prevent unnecessary asset concatting for main portal CSS file.

- modules/admin/app/views/admin/documentaryUnit/createDescription.scala.html
- modules/admin/app/views/admin/virtualUnit/createDescription.scala.html
When there's an error in the form is was rerendering the errored description as hidden, which meant you couldn't update it.
> Fix the create description form

- modules/admin/app/assets/js/vocabeditor.js
This makes it clearer the user needs to add the description when complete.
> Prevent saving item data when the new description form is active

- conf/search.conf
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
This allows adding, e.g. the mm parameter and other arbitrary Solr tuning params, subject to certain constraints such as the keys not overlapping.
> Switch of default AND mode and add means to read Solr params from config

- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/documentaryUnit/listItem.scala.html
- modules/portal/conf/messages
These were hard to find before. Also ensure that we can get to an item's detail page even if it has not descriptions.
> Add an admin facet for items which have restricted visibility.

- modules/core/app/utils/i18n/package.scala
- modules/portal/conf/messages
- modules/portal/test/views/HelpersSpec.scala
This allows more flexibility when country names change more
frequently than JDK is updated. Fixes #41
> Ensure locally defined i18n country names override JDK version

- modules/portal/app/assets/js/portal-signedin.js
This fixes an issue where the popover contained no content...
> Whitelist elements used in the markdown cheatsheet.

- modules/portal/app/controllers/portal/base/PortalController.scala
Single quotes were being included in the files name, which was
especially ugly.
> Fix quoting of filename in XML download content disposition.

- modules/portal/app/controllers/portal/AuthoritativeSets.scala
- modules/portal/app/controllers/portal/Vocabularies.scala
- modules/portal/app/views/authoritativeSet/list.scala.html
- modules/portal/app/views/vocabulary/list.scala.html
Previously the vocabularies and authoritative sets pages allowed users to search only (promoted) vocabs and sets. However this is pretty useless and counter-intuitive since there are only a handful of either.
This change returns results for their *contents* instead of the holders.
The main problem here is that it's different behaviour to the other search pages.
> Change behaviour of vocabs and sets pages to query contents.

- conf/search.conf
- modules/core/app/services/search/SearchConstants.scala
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
This allows us to better locate things by accession or record group
number.
> Add otherIdentifiers field to default search.

- modules/admin/app/views/admin/link/listItem.scala.html
- modules/admin/app/views/admin/link/show.scala.html
- modules/core/app/models/Link.scala
- modules/portal/app/assets/css/ehri/_descriptions.scss
- modules/portal/app/views/common/annotationLinks.scala.html
- modules/portal/app/views/common/link.scala.html
- modules/portal/app/views/link/show.scala.html
- modules/portal/conf/messages
- Copy links are now shown in their own lists
- Link lists are height restricted so they don't take over the page
- Link lists are sorted by target
> Improvements to better highlight/display copy links

- modules/portal/app/assets/css/portal/_style.scss
This is a workaround for the underlying issue, which is that
text truncation occasionally breaks markdown formatting and allows
long URLs etc to overflow the search list width.
> Prevent occasional overflow of search items by dodgy markdown

- modules/portal/app/assets/css/portal/_style.scss
- modules/portal/app/views/common/accountHeaderRightMenu.scala.html
This uses a css property with background-size: cover instead of a image tag with a fixed width and height.
> Prevent squashing on the account icon

- modules/admin/app/services/ingest/IngestApiService.scala
- modules/portal/app/views/common/head.scala.html
Amazingly, YYYY on a java.time.DateTimeFormatter pattern means year of week, and is thus wrong for our purposes a few days of the year! Replaced with 'u', which apparently just means the year (of day.)
> Fix two small date issues: copyright on meta tag and year formatter.

- conf/application.conf
- modules/portal/app/controllers/portal/users/UserProfiles.scala
- modules/portal/conf/messages
- define max size in MB and read config to bytes
- add logging
- fix typo in text error string
No luck attempting to resolve #1198 though.
> Minor improvements to profile image upload

- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/test/auth/oauth2/providers/MicrosoftOAuth2ProviderSpec.scala
They might have set it explicitly or via other means.
> Don't update a user's name when logging in via OAuth2 accounts

- build.sbt
Getting "Received resultset tuples, but no field structure for them" error after changing some DB permissions.
> Update Postgresql JDBC driver to fix IllegalStateException

- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/app/views/admin/authoritativeSet/create.scala.html
- modules/admin/app/views/admin/authoritativeSet/edit.scala.html
- modules/admin/app/views/admin/authoritativeSet/form.scala.html
- modules/admin/app/views/admin/country/create.scala.html
- modules/admin/app/views/admin/country/edit.scala.html
- modules/admin/app/views/admin/country/form.scala.html
- modules/admin/app/views/admin/documentaryUnit/create.scala.html
- modules/admin/app/views/admin/documentaryUnit/edit.scala.html
- modules/admin/app/views/admin/documentaryUnit/form.scala.html
- modules/admin/app/views/admin/documentaryUnit/rename.scala.html
- modules/admin/app/views/admin/repository/create.scala.html
- modules/admin/app/views/admin/repository/edit.scala.html
- modules/admin/app/views/admin/repository/form.scala.html
- modules/admin/app/views/admin/vocabulary/create.scala.html
- modules/admin/app/views/admin/vocabulary/edit.scala.html
- modules/admin/app/views/admin/vocabulary/form.scala.html
- modules/admin/conf/messages
- modules/admin/conf/units.routes
- modules/backend/src/main/scala/services/data/DataApi.scala
- modules/backend/src/main/scala/services/data/DataApiService.scala
- test/integration/admin/DocumentaryUnitViewsSpec.scala
For other hierarchical types, renaming is discouraged via the form, and should be done using the utility rename function.
> Add a dedicated method for changing doc unit identifiers via WS

- conf/search.conf
All things being equal, we want repositories to get a boost over other types of data when the are in a result set.
> Add a boost query (bq) clause to the default search conf.

- app/Module.scala
- modules/admin/app/controllers/units/DocumentaryUnits.scala
- modules/admin/conf/units.routes
- modules/backend/src/main/scala/services/data/DataApiService.scala
- modules/core/app/services/search/GidSearchResolver.scala
- modules/portal/app/services/search/AkkaStreamsIndexMediator.scala
Akka indexer was not clearing the right IDs on deletion, which corrupted the index in some cases.
Additional tweak to redirect to the parent item on child delete.
> Reinstate GID index mediator but fix bug w/ indexer

- build.sbt
- modules/portal/app/assets/js/lib/typeahead.bundle-1.3.1.js
- modules/portal/app/assets/js/portal.js
- modules/portal/app/views/common/primaryHeader.scala.html
- modules/portal/app/views/common/search/searchBar.scala.html
- modules/portal/app/views/layout/portalLayout.scala.html
- update typeahead to commonjs-typeahead 1.3.1
- remove browser autocomplete on search boxes by default
- limit quicksearch types to repositories and countries
> First steps to improving search autocomplete

- modules/core/app/controllers/generic/Read.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
For 404s it's useful to know the UA in case it's a crawler. For OAuth2 errors the referer and UA might help to pin these down.
> Log referrer and user-agent for some more mysterious error cases.

- .github/workflows/ci.yml
- modules/portal/app/services/storage/S3CompatibleFileStorage.scala
- test/services/storage/S3CompatibleFileStorageSpec.scala
This should have been a no-op, but instead we issued an S3 API call.
Also fix the stupid CI config error that prevented me noticing this for so long - shouldn't have doubted the CircleCI setup!
> Fix an error when deleting a storage prefix with no matching files

- modules/admin/app/controllers/links/Links.scala
- modules/guides/app/controllers/portal/guides/Guides.scala
- modules/portal/app/controllers/base/SearchVC.scala
- modules/portal/app/controllers/portal/Bookmarks.scala
- modules/portal/app/services/storage/S3CompatibleFileStorage.scala
- test/services/feedback/SqlFeedbackServiceSpec.scala
- test/services/harvesting/MockHarvestEventService.scala
- test/services/ingest/SqlImportLogServiceSpec.scala
Convert literal uses of `Unit` to `()`: where the `->` tuple builder is used these are converted to raw tuples to avoid issues with inferred arguments w/ Scala 2.12.
> More Scala 2.13 compat fixes

- modules/portal/app/assets/js/common.js
- modules/portal/app/assets/js/portal.js
- modules/solr/src/main/scala/eu/ehri/project/search/solr/SolrQueryBuilder.scala
- project/build.properties
- JS to append inline=true query param was broken
- pattern matching against `Unit` in the query builder also broken
Also downgrade to SBT 1.3.13 since 1.4.0 has an issue with swallowing Play crash reporting in the browser.
> Fix some issues with virtual collection searching and listing

- modules/backend/src/main/scala/utils/http/package.scala
- modules/core/src/main/scala/auth/sso/DiscourseSSO.scala
- modules/core/src/main/scala/models/UserProfile.scala
- modules/core/src/test/scala/auth/sso/DiscourseSSOSpec.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/app/views/errors/verifiedOnly.scala.html
- modules/portal/app/views/userProfile/unverified.scala.html
- modules/portal/conf/account.routes
- modules/portal/conf/messages
- modules/portal/conf/messages.de
- modules/portal/conf/messages.fr
- modules/portal/conf/messages.pl
- test/integration/portal/AccountsSpec.scala
This is an SSO mechanism to allow us to set up client sites that use the portal's user credentials for login. Discourse is the obvious first candidate but eventually the editions could also use this mechanism, since it seems relatively simple.
> Add an endpoint to facilitate integration with Discourse Connect

- build.sbt
- modules/admin/app/actors/transformation/XmlConverter.scala
- modules/admin/app/assets/js/datamanager/worker.js
- modules/portal/app/services/storage/S3CompatibleFileStorage.scala
- test/actors/transformation/XmlConverterSpec.scala
- EAD manager UI can read non-UTF8 input sources correctly
- XML converter will transcode to UTF-8 automatically when needed
However: there's currently no way to upload non-UTF-8 files since the browser apparently doesn't set this info. Presumably this would be a dataset-level setting that would prompt a transcoding step.
> Start of better handling for non-UTF-8 input datasets

- conf/evolutions/default/1.sql
- etc/db_migrations/20210722_add_content_type_to_import_dataset.sql
- modules/admin/app/actors/transformation/XmlConverter.scala
- modules/admin/app/actors/transformation/XmlConverterManager.scala
- modules/admin/app/assets/js/datamanager/app.vue
- modules/admin/app/assets/js/datamanager/components/_manager-datasets.vue
- modules/admin/app/assets/js/datamanager/components/_manager-oaipmh.vue
- modules/admin/app/assets/js/datamanager/components/_manager-rs.vue
- modules/admin/app/assets/js/datamanager/components/_manager-upload.vue
- modules/admin/app/assets/js/datamanager/components/_mixin-preview-panel.vue
- modules/admin/app/assets/js/datamanager/components/_modal-dataset-config.vue
- modules/admin/app/assets/js/datamanager/types.ts
- modules/admin/app/assets/js/datamanager/worker.js
- modules/admin/app/controllers/datasets/DataTransformations.scala
- modules/admin/app/controllers/datasets/ImportConfigs.scala
- modules/admin/app/models/ImportDataset.scala
- modules/admin/app/services/datasets/ImportDatasetService.scala
- modules/admin/app/services/datasets/SqlImportDatasetService.scala
- modules/admin/app/services/transformation/WrappingXmlTransformer.scala
- modules/admin/app/services/transformation/utils/package.scala
- modules/admin/conf/transform.xqy
- modules/admin/test/services/transformation/BaseXXQueryXmlTransformerSpec.scala
- test/integration/admin/DataTransformationsSpec.scala
- Now transcode to UTF-8 when doing single-file previews
- Add a content type field to the dataset model. This will override whatever the content type of the file is.
- Use the dataset content type to figure out how to decode previewed
files in the UI
> More handling for non-UTF-8 content types

- modules/backend/src/main/scala/services/data/DataServiceError.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/conf/messages
- test/integration/portal/SignupSpec.scala
If the portal's default groups aren't present on the backend dev environment the current ItemNotFound error is very confusing. Log an error in this case to the console and return 500 instead of 404.
Fixes #1369
> Fix a misleading error if the backend does not have correct groups

- .gitignore
- modules/portal/app/views/common/footer.scala.html
This aims to close #1373 and adds the .bsp directory to .gitignore.
> Adds FAQ link to the footer using @footerLink

- conf/application.conf
- modules/admin/app/controllers/users/UserProfiles.scala
- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/conf/messages
- test/integration/portal/SignupSpec.scala
This is to prevent signups to staging that break synchronisation
> Allow disabling signup via a config flag.

- modules/admin/app/assets/css/datasets.scss
- modules/admin/app/assets/js/datasets/components/_editor-transformation.vue
- modules/admin/app/assets/js/datasets/components/_editor-urlset.vue
- modules/admin/app/assets/js/datasets/components/_editor-xslt.vue
This also fixes an issue where the XSLT input wouldn't refresh after a paste import
> Workaround Firefox not supporting clipboard.readText

- modules/admin/app/views/admin/Helpers.scala
- modules/portal/app/controllers/base/ImageHelpers.scala
- modules/portal/app/utils/ImageSniffer.java
- modules/portal/test/utils/ImageSnifferSpec.scala
For as-yet-to-be-determined reasons, building on JDK11 caused an error.
> Replace a custom exception with a standard one for compatibility

- conf/application.conf
- modules/core/src/main/scala/config/AppConfig.scala
- modules/portal/app/views/authoritativeSet/itemDetails.scala.html
- modules/portal/app/views/common/exportItem.scala.html
- modules/portal/app/views/concept/itemDetails.scala.html
- modules/portal/app/views/country/itemDetails.scala.html
- modules/portal/app/views/documentaryUnit/itemDetails.scala.html
- modules/portal/app/views/historicalAgent/itemDetails.scala.html
- modules/portal/app/views/repository/itemDetails.scala.html
- modules/portal/app/views/vocabulary/itemDetails.scala.html
- test/integration/portal/PortalSpec.scala
Add configuration that enables adding export proxy URLs down the sidebar on portal items. These are just a label and an URL for which the corresponding URL has been set up to export an item via an external service, e.g. via a proxy server.
> Export proxy URL configuration

- conf/application.conf
- modules/core/src/main/scala/auth/handler/cookie/CookieTokenAccessor.scala
- test/integration/portal/PortalSpec.scala
- test/integration/portal/SignupSpec.scala
This needs to be lax for the time being, since cross-domain cookies are needed for functional OAuth2 logins.
> Add a samesite attribute to the auth cookie.

- modules/admin/app/assets/js/datasets/common.spec.ts
- modules/admin/app/assets/js/datasets/common.ts
This is a bit dangerous for encoding, since values cannot contain tabs (FIXME) but previously it would completely break mapping conversions.
Ultimately we should use a safer format (like JSON) with fewer ambiguities, but until then use Excel-style nothing-is-quoted style.
> Disable quoting on TSV parsing, to avoid mangling Excel format files

- modules/admin/app/assets/js/datasets/components/_manager-dataset-list.vue
It's still useful to be able to batch a single dataset, because you can combine harvesting, conversion and import in one click.
> Don't disable the batch process button when there's only 1 dataset

- conf/application.conf
- modules/api/app/controllers/api/graphql/GraphQL.scala
- modules/backend/src/main/scala/services/data/DataServiceBuilder.scala
- modules/backend/src/main/scala/services/data/WsDataService.scala
- modules/portal/app/controllers/portal/base/PortalController.scala
e.g. GraphQL and EAD endpoints
> Set an extended timeout to endpoints that might stream a lot of data

- conf/evolutions/default/1.sql
- etc/db_migrations/20230914_add_import_config_batch_size_column.sql
- modules/admin/app/actors/cleanup/CleanupRunner.scala
- modules/admin/app/actors/ingest/DataImporter.scala
- modules/admin/app/actors/ingest/DataImporterManager.scala
- modules/admin/app/assets/js/datasets/components/_manager-dataset.vue
- modules/admin/app/assets/js/datasets/components/_manager-snapshots.vue
- modules/admin/app/assets/js/datasets/components/_modal-batch-ops.vue
- modules/admin/app/assets/js/datasets/components/_modal-cleanup-config.vue
- modules/admin/app/assets/js/datasets/components/_modal-ingest-config.vue
- modules/admin/app/assets/js/datasets/types.ts
- modules/admin/app/controllers/admin/Ingest.scala
- modules/admin/app/controllers/datasets/ImportConfigs.scala
- modules/admin/app/models/ImportConfig.scala
- modules/admin/app/services/ingest/IngestService.scala
- modules/admin/app/services/ingest/SqlImportConfigService.scala
- modules/admin/app/services/ingest/WSIngestService.scala
- modules/portal/app/services/search/AkkaStreamsIndexMediator.scala
- test/actors/ingest/DataImporterManagerSpec.scala
- test/actors/ingest/DataImporterSpec.scala
- test/services/ingest/MockIngestService.scala
This is basically only for the USHMM `collections` dataset, which exhausts memory on the backend when imported.
> Make it possible to import large datasets in batches

- modules/admin/app/assets/css/datasets.scss
- modules/admin/app/assets/js/datasets/api.ts
- modules/admin/app/assets/js/datasets/components/_modal-batch-ops.vue
- modules/admin/app/assets/js/datasets/components/_modal-ingest-config.vue
- modules/admin/app/assets/js/datasets/types.ts
- modules/admin/app/controllers/datasets/ImportDatasets.scala
- modules/admin/app/controllers/datasets/ImportFiles.scala
- modules/admin/conf/datasets.routes
- modules/portal/app/services/storage/FileStorage.scala
- modules/portal/app/services/storage/S3CompatibleFileStorage.scala
- test/integration/admin/ImportFilesSpec.scala
- test/services/storage/MockFileStorage.scala
- test/services/storage/S3CompatibleFileStorageSpec.scala
This went down a bit of a rabbit hole and ended up involving a lot of changes to achieve idempotent copying. Might want to rework the storage API to not always use multi-part upload, since this results in eTags that are different from non-multipart uploads.
> When batch-copying import configs, also copy properties files

- modules/portal/app/services/search/AkkaStreamsIndexMediator.scala
This is kind of grasping at straws to fix the mysterious bug where the index is populated with dodgy data seemingly from two items, but it seems likely to be a reentrancy issue somewhere. This should prevent any state in the JsonConverter lingering betwen ops.
> Reinitialise JSON converter for each index operation.

- modules/api/app/controllers/api/v1/ApiV1.scala
- modules/api/conf/messages
This requires an unseemly substitution of the API URL prefix with the /unit one, so it won't work for types of item yet. That will have to wait for a better solution.
> Hack the Search API error handler to figure out moved units

- build.sbt
- conf/application.conf
- conf/logback-play-dev.xml
- modules/portal/app/controllers/portal/account/Accounts.scala
- modules/portal/app/forms/AccountForms.scala
- modules/portal/app/views/account/changeEmailForm.scala.html
- modules/portal/app/views/account/confirmEmail.scala.html
- modules/portal/conf/account.routes
- modules/portal/conf/messages
- test/helpers/TestConfiguration.scala
- test/integration/portal/AccountsSpec.scala
- test/services/accounts/MockAccountManager.scala
This is because some mail hosts follow links to check for malware and this makes the user's attempt to verify fail, confusing them.
Also improve some language strings.
> Require POST to confirm email addresses

- modules/portal/app/assets/css/portal/_style.scss
- modules/portal/app/views/index.scala.html
This was caused by changing the OAuth login icons and forgetting they were also used here! CSS  strikes again.
Also adjust homepage grid to behave better with responsive scaling.
> Fix various styling issues on the home page

- modules/portal/app/assets/css/portal/_style.scss
- modules/portal/app/controllers/portal/Portal.scala
- modules/portal/app/services/htmlpages/GoogleDocsHtmlPages.scala
- modules/portal/app/services/htmlpages/HtmlPages.scala
- modules/portal/app/services/search/AkkaStreamsIndexMediator.scala
- modules/portal/conf/portal.routes
- test/integration/portal/PortalSpec.scala
- test/mockdata/package.scala
- test/services/htmlpages/MockHtmlPages.scala
The Docs title is used if no i18n one is defined
> Tweak the Google Docs external page feature to support native titles

- modules/admin/app/services/ingest/RelaxNGEadValidator.scala
- modules/xslt/src/main/scala/eu/ehri/project/xml/SaxonXsltXmlTransformer.scala
- modules/xslt/src/main/scala/eu/ehri/project/xml/XsltXmlTransformer.scala
- modules/xslt/src/test/scala/eu/ehri/project/xml/SaxonXsltXmlTransformerSpec.scala
DTDs are ignored, since I'm not sure what else would work here. Only the Saxon XSLT processor seemed to choke for UTF-8 files w/ BOMs.
> Make the various validators more robust to BOMs and DTD resolution
